import CMVCurvatureIntegration

namespace CMVCurvatureIntegration

#print axioms eqOn_Icc_of_hasDerivAt_zero
#print axioms UnitSpeedConstantCurvatureOn.center_fst_hasDerivAt_zero
#print axioms UnitSpeedConstantCurvatureOn.center_snd_hasDerivAt_zero
#print axioms UnitSpeedConstantCurvatureOn.center_invariant
#print axioms UnitSpeedConstantCurvatureOn.closed_circle_identity
#print axioms UnitSpeedConstantCurvatureOn.closed_endpoints_circle_identity
#print axioms UnitSpeedConstantCurvatureOn.closed_circle_identity_of_positive_radius
#print axioms UnitSpeedConstantCurvatureOn.closed_circle_identity_of_negative_radius

#print axioms ArbitrarySpeedConstantCurvatureOn.speed_hasDerivAt
#print axioms ArbitrarySpeedConstantCurvatureOn.normalized_tangent_fst_hasDerivAt
#print axioms ArbitrarySpeedConstantCurvatureOn.normalized_tangent_snd_hasDerivAt
#print axioms ArbitrarySpeedConstantCurvatureOn.trace_fst_hasDerivAt_speed_mul_tangent
#print axioms ArbitrarySpeedConstantCurvatureOn.trace_snd_hasDerivAt_speed_mul_tangent
#print axioms ArbitrarySpeedConstantCurvatureOn.normalized_tangent_fst_frenet
#print axioms ArbitrarySpeedConstantCurvatureOn.normalized_tangent_snd_frenet
#print axioms ArbitrarySpeedConstantCurvatureOn.normalized_tangent_differential_equation
#print axioms ArbitrarySpeedConstantCurvatureOn.center_invariant
#print axioms ArbitrarySpeedConstantCurvatureOn.closed_circle_identity
#print axioms ArbitrarySpeedConstantCurvatureOn.closed_endpoints_circle_identity
#print axioms ArbitrarySpeedConstantCurvatureOn.closed_circle_identity_of_positive_radius
#print axioms ArbitrarySpeedConstantCurvatureOn.closed_circle_identity_of_negative_radius

end CMVCurvatureIntegration
