import CMVCanonicalLowerBound

#print axioms CMVRelaxation.SmoothSequence.cost_add_ge_of_pointwise_add_distance
#print axioms CMVRelaxation.CandidateFourArc.frontierCost_le_smoothSequence_cost_add_deficit
#print axioms CMVRelaxation.CandidateFourArc.frontierCost_le_smoothSequence_cost
#print axioms CMVRelaxation.CandidateFourArc.frontierCost_le_relaxedPerimeter
#print axioms CMVRelaxation.CandidateFourArc.endpoint_frontierWeightedPerimeter
#print axioms CMVRelaxation.CandidateFourArc.endpoint_frontierCost_le_relaxedPerimeter
#print axioms CMVRelaxation.CanonicalFourArc.frontierCost_le_smoothSequence_cost_add_deficit
#print axioms CMVRelaxation.CanonicalFourArc.frontierCost_le_smoothSequence_cost
#print axioms CMVRelaxation.CanonicalFourArc.frontierCost_le_relaxedPerimeter
