import CMVFigureFiveOrientedLoopLocalization

#print axioms CMVFigureFive.SourceGeometry.hasOpenRectangularLocalization
#print axioms CMVFigureFive.SourceGeometry.exists_localizedFiniteJunctionBoundaryAtlases
#print axioms CMVFigureFive.SourceGeometry.exists_localizedBoundaryHalfSpaceAtlases
#print axioms CMVFigureFive.SourceGeometry.exists_localizedFiniteBoundaryTopologies
#print axioms
  CMVFigureFive.SourceGeometry.exists_localizedFinitePiecewiseRegularBoundaryTopologies
#print axioms
  CMVFigureFive.SourceGeometry.exists_localizedOccupiedLeftArcBranchAssignments
#print axioms
  CMVFigureFive.SourceGeometry.exists_localizedTransverseEndpointTraces
#print axioms CMVFigureFive.SourceGeometry.exists_localizedCleanCornerCutTraces
#print axioms CMVFigureFive.SourceGeometry.exists_localizedFiniteBoundaryIncidences
#print axioms CMVFigureFive.SourceGeometry.exists_localizedFiniteBoundaryCyclicTraversals
#print axioms CMVFigureFive.SourceGeometry.exists_localizedFiniteBoundaryGeometricTraversals
#print axioms
  CMVFigureFive.SourceGeometry.exists_localizedFiniteBoundaryClosedWalkPaths
