import CMVFigureThreeBoundaryRealization

namespace CMVFigureThree

#print axioms VerticalOrientation.normalizeAddedCap_radius
#print axioms VerticalOrientation.normalizePoint_added_arcPoint
#print axioms VerticalOrientation.normalizePoint_image_chordCarrier
#print axioms SourceIncidence.added_chordCarrier_subset_tangentInterval
#print axioms SourceIncidence.normalizedAddedCap_baseY
#print axioms SourceIncidence.normalizedAddedCap_radius
#print axioms SourceIncidence.normalizedAddedCap_contactLaw
#print axioms SourceIncidence.normalized_added_chordCarrier_subset_horizontalSection
#print axioms SourceIncidence.strictRadius_false
#print axioms SourceIncidence.sourceRadius_eq_one
#print axioms ActualBoundaryRealization.toSourceIncidence
#print axioms ActualBoundaryRealization.actual_frontier_eq_boundaryTrace
#print axioms ActualBoundaryRealization.primaryExterior_arcTrace_subset_frontier
#print axioms ActualBoundaryRealization.leftStripArcTrace_subset_frontier
#print axioms ActualBoundaryRealization.rightStripArcTrace_subset_frontier
#print axioms ActualBoundaryRealization.addedExterior_arcTrace_subset_frontier
#print axioms ActualBoundaryRealization.leftInterfaceTrace_subset_frontier
#print axioms ActualBoundaryRealization.rightInterfaceTrace_subset_frontier
#print axioms ActualBoundaryRealization.primaryLeft_mem_frontier
#print axioms ActualBoundaryRealization.primaryRight_mem_frontier
#print axioms ActualBoundaryRealization.strictRadius_false
#print axioms ActualBoundaryRealization.sourceRadius_eq_one

end CMVFigureThree
