import CMVFigureFourComplementTopologyExamples

#print axioms CMVFigureFourComplementTopology.mem_of_mem_same_height_of_abs_sub_le
#print axioms CMVFigureFourComplementTopology.verticalSpine_mem_interior
#print axioms CMVFigureFourComplementTopology.horizontal_contraction_mem_interior
#print axioms CMVFigureFourComplementTopology.interior_horizontal_spine_joinedIn
#print axioms CMVFigureFourComplementTopology.isPathConnected_compl_of_bounded_centeredSections

#print axioms
  CMVSourceClassification.RawFourArcCoordinates.horizontalSection_empty_or_centered_interval
#print axioms CMVSourceClassification.RawFourArcCoordinates.isBounded_carrier
#print axioms CMVSourceClassification.RawFourArcCoordinates.carrier_vertical_bounds
#print axioms
  CMVSourceClassification.RawFourArcCoordinates.axis_mem_interior_of_abs_lt_verticalExtent
#print axioms CMVSourceClassification.RawFourArcCoordinates.interior_vertical_bounds
#print axioms CMVSourceClassification.RawFourArcCoordinates.interior_spine_joinedIn
#print axioms CMVSourceClassification.RawFourArcCoordinates.isPathConnected_interior_carrier
#print axioms CMVSourceClassification.RawFourArcCoordinates.isPathConnected_exterior_carrier
#print axioms CMVSourceClassification.RawFourArcCoordinates.exists_exterior_escape_anchor
#print axioms
  CMVSourceClassification.RawFourArcCoordinates.compl_frontier_carrier_eq_interior_union_exterior
#print axioms CMVSourceClassification.RawFourArcCoordinates.disjoint_interior_carrier_compl

#print axioms CMVFigureFour.Examples.strictBilateralSourceAt_complement_topology
#print axioms CMVFigureFour.Examples.endpointBilateralSourceAt_complement_topology
#print axioms CMVFigureFour.Examples.strictTranslated_complement_topology
#print axioms CMVFigureFour.Examples.endpointTranslated_complement_topology
