import CMVFigureThreeSourceExtraction

namespace CMVFigureThree

#print axioms SourceBoundaryExtraction.InterfaceEndpointOrder.toInterfaceIncidenceData
#print axioms SourceBoundaryExtraction.FigureThreeBranchSelection.toPiecewiseRegularBoundaryTrace
#print axioms RegularFigureThreeBoundaryConfiguration.leftInterface
#print axioms RegularFigureThreeBoundaryConfiguration.rightInterface
#print axioms RegularFigureThreeBoundaryConfiguration.interfaceIncidence
#print axioms RegularFigureThreeBoundaryConfiguration.piecewiseBoundary
#print axioms SourceBoundaryExtraction.PiecewiseRegularBoundaryTrace.parameter_mem_piece
#print axioms SourceBoundaryExtraction.PiecewiseRegularBoundaryTrace.primary_actual
#print axioms SourceBoundaryExtraction.PiecewiseRegularBoundaryTrace.left_strip_actual
#print axioms SourceBoundaryExtraction.PiecewiseRegularBoundaryTrace.right_strip_actual
#print axioms SourceBoundaryExtraction.PiecewiseRegularBoundaryTrace.added_actual
#print axioms SourceBoundaryExtraction.PiecewiseRegularBoundaryTrace.left_interface_actual
#print axioms SourceBoundaryExtraction.PiecewiseRegularBoundaryTrace.right_interface_actual
#print axioms SourceBoundaryExtraction.PiecewiseRegularBoundaryTrace.frontier_exhaustive
#print axioms SourceBoundaryExtraction.PiecewiseRegularBoundaryTrace.toConfigurationEnumerationData
#print axioms RegularFigureThreeBoundaryConfiguration.configurationEnumeration

#print axioms RegularFigureThreeBoundaryConfiguration.primary_left_on_left_trace
#print axioms RegularFigureThreeBoundaryConfiguration.primary_right_on_right_trace
#print axioms RegularFigureThreeBoundaryConfiguration.leftInterface_carrier_eq_interfaceTrace
#print axioms RegularFigureThreeBoundaryConfiguration.rightInterface_carrier_eq_interfaceTrace
#print axioms RegularFigureThreeBoundaryConfiguration.left_segment_order
#print axioms RegularFigureThreeBoundaryConfiguration.right_segment_order
#print axioms RegularFigureThreeBoundaryConfiguration.frontier_eq_boundaryTrace
#print axioms RegularFigureThreeBoundaryConfiguration.toActualBoundaryRealization
#print axioms RegularFigureThreeBoundaryConfiguration.toActualBoundaryRealization_carrier
#print axioms RegularFigureThreeBoundaryConfiguration.toActualBoundaryRealization_sourceRadius
#print axioms RegularFigureThreeBoundaryConfiguration.strictRadius_false
#print axioms RegularFigureThreeBoundaryConfiguration.sourceRadius_eq_one
#print axioms not_exists_regularFigureThree_strictRadius

end CMVFigureThree
