import CMVFigureFiveScalarComparison

#print axioms CMVFigureFive.CappedInterface.cap_endpoints_between
#print axioms CMVFigureFive.SourceGeometry.width_pos
#print axioms CMVFigureFive.SourceGeometry.leftStripCenter_snd_eq_zero
#print axioms CMVFigureFive.SourceGeometry.rightStripCenter_snd_eq_zero
#print axioms CMVFigureFive.SourceGeometry.sourceRadius_eq_one
#print axioms CMVFigureFive.SourceGeometry.sourceCarrier_nullMeasurableSet
#print axioms CMVFigureFive.SourceGeometry.one_or_two_exterior_caps
#print axioms LeanSuffixAnalytic.typeThreeArea_continuousAt_one
#print axioms LeanSuffixAnalytic.typeThreeArea_le_max_endpoints
#print axioms LeanSuffixAnalytic.typeThreeAreaSupport_hasDerivAt
#print axioms LeanSuffixAnalytic.typeThreeAreaSupport_continuousOn_Icc
#print axioms CMVFigureFive.angularArea_eq_typeThreeArea
#print axioms CMVFigureFive.angularArea_hasDerivAt_zero
#print axioms CMVFigureFive.exists_regular_height_area_lt_endpoint
#print axioms CMVFigureFive.typeThree_endpoint_support
#print axioms CMVFigureFive.exists_regular_typeThree_below_endpoint_support
#print axioms CMVFigureFive.exists_admissible_typeThree_below_endpoint_support
#print axioms CMVFigureFive.volume_degenerateHorizontalSegment
#print axioms CMVFigureFive.volume_capArcTrace
#print axioms CMVFigureFive.volume_stripCircleTrace
#print axioms CMVFigureFive.CappedInterface.theta_eq_endpointAngle
#print axioms CMVFigureFive.CappedInterface.chord_eq_two_mul_sin_endpointAngle
#print axioms CMVFigureFive.CappedInterface.arcLength_eq_two_mul_endpointAngle
#print axioms CMVFigureFive.CappedInterface.euclideanArea_eq_endpointAngle_sub
#print axioms CMVFigureFive.CappedInterface.weightedAreaContribution_eq_endpointGap
#print axioms
  CMVFigureFive.CappedInterface.weightedArc_sub_chord_eq_two_mul_endpointGap
#print axioms CMVFigureFive.CappedInterface.chord_le_tangent_span
#print axioms CMVFigureFive.InterfaceBoundary.volume_trace
#print axioms CMVFigureFive.InterfaceBoundary.weightedAreaContribution_eq
#print axioms CMVFigureFive.InterfaceBoundary.weightedBoundaryCost_eq
#print axioms CMVFigureFive.SourceGeometry.volume_frontier_representative
#print axioms CMVFigureFive.SourceGeometry.sourceCarrier_ae_closure_representative
#print axioms CMVFigureFive.SourceGeometry.weightedArea_sourceCarrier_eq_closure
#print axioms CMVFigureFive.SourceGeometry.relaxedPerimeter_sourceCarrier_eq_closure
#print axioms CMVFigureFive.SourceGeometry.capCount_eq_one_or_two
#print axioms CMVFigureFive.SourceGeometry.endpointChord_le_width
#print axioms CMVFigureFive.SourceGeometry.modeledWeightedArea_eq
#print axioms CMVFigureFive.SourceGeometry.modeledWeightedPerimeter_eq
#print axioms
  CMVFigureFive.SourceGeometry.modeledWeightedPerimeter_sub_modeledWeightedArea
#print axioms CMVFigureFive.SourceGeometry.typeThreeArea_one_eq
#print axioms CMVFigureFive.SourceGeometry.typeThreeArea_one_le_modeledWeightedArea
#print axioms
  CMVFigureFive.SourceGeometry.modeledWeightedArea_add_support_le_modeledWeightedPerimeter
#print axioms
  CMVFigureFive.SourceGeometry.exists_admissible_typeThree_below_modeledWeightedPerimeter
