import CMVLiteralCornerShortening

namespace CMVRelaxation.LiteralCornerShortening

#print axioms exteriorInterfaceSpecimen_carrier
#print axioms exteriorInterfaceCompetitor_carrier
#print axioms densityOneNontangentialSpecimen_carrier
#print axioms densityOneNontangentialCompetitor_carrier
#print axioms exteriorInterfaceCompetitor_subset_specimen
#print axioms densityOneNontangentialCompetitor_subset_specimen

#print axioms exteriorInterfaceSpecimen_frontier
#print axioms exteriorInterfaceCompetitor_frontier
#print axioms densityOneNontangentialSpecimen_frontier
#print axioms densityOneNontangentialCompetitor_frontier

#print axioms weightedTraceCost_interfaceTrace
#print axioms weightedTraceCost_exteriorIncidentTrace
#print axioms weightedTraceCost_exteriorShortcutTrace
#print axioms weightedTraceCost_densityOneIncidentTrace
#print axioms weightedTraceCost_densityOneShortcutTrace
#print axioms interfaceTrace_subset_exterior_specimen_frontier
#print axioms exteriorIncidentTrace_subset_specimen_frontier
#print axioms exteriorShortcutTrace_subset_competitor_frontier
#print axioms densityOneIncidentTrace_subset_specimen_frontier
#print axioms densityOneShortcutTrace_subset_competitor_frontier

#print axioms exterior_incident_meets_interface_only_at_corner
#print axioms densityOne_incident_meets_interface_only_at_corner
#print axioms incident_ray_is_regular_and_nontangential
#print axioms densityOne_complete_frontiers_have_density_one

#print axioms exteriorInterfaceSpecimen_complete_frontier_cost
#print axioms exteriorInterfaceCompetitor_complete_frontier_cost
#print axioms densityOneNontangentialSpecimen_complete_frontier_cost
#print axioms densityOneNontangentialCompetitor_complete_frontier_cost
#print axioms exteriorInterface_exact_frontier_change
#print axioms exteriorInterface_strict_frontier_gain
#print axioms densityOne_exact_frontier_change
#print axioms densityOne_strict_frontier_gain

#print axioms exteriorInterfaceSpecimen_weightedArea
#print axioms exteriorInterfaceCompetitor_weightedArea
#print axioms densityOneNontangentialSpecimen_weightedArea
#print axioms densityOneNontangentialCompetitor_weightedArea
#print axioms exteriorInterface_weightedArea_defect_exact
#print axioms densityOne_weightedArea_defect_exact
#print axioms weightedArea_defects_le_one_mul_r_sq

#print axioms lambdaTwo_literal_corner_shortening_gate

end CMVRelaxation.LiteralCornerShortening
