import CMVFiniteCornerRepair

#print axioms CMVRelaxation.IsSmoothDomain.of_locally_eq
#print axioms CMVRelaxation.frontier_inter_eq_of_inter_open_eq
#print axioms
  CMVRelaxation.frontierMeasure_restrict_eq_of_frontier_inter_eq
#print axioms
  CMVRelaxation.frontierMeasure_restrict_eq_of_inter_open_eq
#print axioms CMVRelaxation.smoothCostOn_eq_of_frontier_inter_eq
#print axioms CMVRelaxation.smoothCostOn_eq_of_inter_open_eq
#print axioms CMVRelaxation.smoothCostOn_add_compl
#print axioms
  CMVRelaxation.RigidProjectionPatch.finset_sum_payoff_le_smoothCostOn_add_error
#print axioms
  CMVRelaxation.SmoothSequence.finset_sum_payoff_le_liminf_smoothCostOn
#print axioms CMVRelaxation.RigidProjectionPatch.lowerCollar_subset_window
#print axioms CMVRelaxation.RigidProjectionPatch.upperCollar_subset_window
#print axioms CMVRelaxation.RigidProjectionPatch.changeCarrierOnWindow
#print axioms CMVRelaxation.exists_contDiff_infty_deriv_close_anchor
#print axioms CMVRelaxation.abs_graphSpeed_sub_graphSpeed_le
#print axioms CMVRelaxation.tangentComplexEquiv
#print axioms CMVRelaxation.graphTangentFrame
#print axioms CMVRelaxation.euclideanRigidMap_graphTangentFrame
#print axioms CMVRelaxation.graphTangentFrame_normal_displacement
#print axioms CMVRelaxation.subgraphTangentPatch
#print axioms CMVRelaxation.supergraphTangentFrame
#print axioms CMVRelaxation.euclideanRigidMap_supergraphTangentFrame
#print axioms CMVRelaxation.supergraphTangentFrame_normal_displacement
#print axioms CMVRelaxation.supergraphTangentPatch
#print axioms CMVRelaxation.abs_graphTangentFrame_fst_sub_le
#print axioms CMVRelaxation.abs_supergraphTangentFrame_fst_sub_le
#print axioms CMVRelaxation.tangentBox_residual_lt_of_bound
#print axioms CMVRelaxation.abs_sub_tangent_le_of_deriv_close
#print axioms CMVRelaxation.exists_uniform_deriv_close_on_Icc
#print axioms CMVRelaxation.exists_uniform_tangent_remainder_on_Icc
#print axioms CMVRelaxation.exists_contDiff_infty_graphLength_close_anchor
#print axioms CMVRelaxation.isSmoothDomain_subgraph
#print axioms CMVRelaxation.isSmoothDomain_supergraph
#print axioms CMVTwoPatchGraphVariation.GraphPatch.isSmoothDomain_occupiedGraphDomain
#print axioms CMVTwoPatchGraphVariation.GraphPatch.frontier_occupiedGraphDomain
#print axioms CMVTwoPatchGraphVariation.GraphPatch.Tube.half
#print axioms
  CMVTwoPatchGraphVariation.GraphPatch.exists_smoothGraph_weightedLength_close
#print axioms
  CMVTwoPatchGraphVariation.GraphPatch.exists_smoothGraph_in_tube_weightedLength_close
#print axioms
  CMVTwoPatchGraphVariation.GraphPatch.mem_carrier_iff_mem_occupiedGraphDomain_of_mem_graphTube
#print axioms
  CMVTwoPatchGraphVariation.GraphPatch.exists_smoothGraph_in_tube_weightedLength_lt
#print axioms CMVTwoPatchGraphVariation.GraphPatch.tangentFrame
#print axioms
  CMVTwoPatchGraphVariation.GraphPatch.tangentProjectionBox_subset_graphTube
#print axioms
  CMVTwoPatchGraphVariation.GraphPatch.exists_tangentProjectionBox_in_graphTube
#print axioms
  CMVTwoPatchGraphVariation.GraphPatch.tangentRigidProjectionPatch
#print axioms
  CMVTwoPatchGraphVariation.GraphPatch.tangentRigidProjectionPatch_carrier
#print axioms
CMVTwoPatchGraphVariation.GraphPatch.mem_variedCarrier_iff_mem_occupiedGraphDomain_of_mem_graphTube
#print axioms CMVTwoPatchGraphVariation.exists_compact_interval_of_tsupport_subset
#print axioms CMVTwoPatchGraphVariation.PrimaryVariation.exists_compact_support_interval
#print axioms CMVTwoPatchGraphVariation.exists_compact_support_interval_velocityTwo
#print axioms CMVTwoPatchGraphVariation.ActualTwoPatchData.actualCarrier_inter_firstGraphTube
#print axioms CMVTwoPatchGraphVariation.ActualTwoPatchData.actualCarrier_inter_secondGraphTube
#print axioms CMVTwoPatchGraphVariation.ActualTwoPatchData.variedCarrier_inter_firstGraphTube
#print axioms CMVTwoPatchGraphVariation.ActualTwoPatchData.variedCarrier_inter_secondGraphTube
#print axioms CMVTwoPatchGraphVariation.contDiff_graphBlendCutoff
#print axioms CMVTwoPatchGraphVariation.exists_graphBlendCutoff_deriv_bound
#print axioms CMVTwoPatchGraphVariation.contDiff_blendGraphs
#print axioms CMVTwoPatchGraphVariation.blendGraphs_eq_left
#print axioms CMVTwoPatchGraphVariation.blendGraphs_eq_right
#print axioms CMVTwoPatchGraphVariation.deriv_blendGraphs
#print axioms CMVTwoPatchGraphVariation.abs_blendGraphs_sub_le
#print axioms CMVTwoPatchGraphVariation.abs_deriv_blendGraphs_sub_le
#print axioms
  CMVTwoPatchGraphVariation.PrimaryVariation.eq_zero_and_deriv_eq_zero_of_not_mem_support_interval
#print axioms
  CMVTwoPatchGraphVariation.GraphPatch.exists_common_smoothGraphs_in_tube_weightedLength_lt
#print axioms CMVRelaxation.volume_closedGraphBand
#print axioms
  CMVTwoPatchGraphVariation.GraphPatch.volume_occupiedGraphDomain_symmDiff_inter_prod_le
#print axioms
  CMVTwoPatchGraphVariation.GraphPatch.volume_occupiedGraphDomain_symmDiff_inter_prod_le_of_uniform
#print axioms
  CMVTwoPatchGraphVariation.GraphPatch.volume_local_occupiedGraphDomain_symmDiff_le_of_uniform
#print axioms CMVRelaxation.isometry_euclideanVerticalEmbedding
#print axioms CMVRelaxation.hausdorffMeasure_verticalLine_inter
#print axioms CMVRelaxation.volume_eq_lintegral_verticalSliceVolume
#print axioms CMVRelaxation.exists_verticalSliceVolume_le_average
#print axioms CMVRelaxation.exists_verticalSeam_disagreement_le
#print axioms
  CMVTwoPatchGraphVariation.GraphPatch.verticalSliceVolume_occupiedGraphDomain_symmDiff
#print axioms
  CMVRelaxation.SmoothSequence.exists_verticalSeams_tendsto_zero
#print axioms
  CMVRelaxation.SmoothSequence.exists_two_verticalSeams_tendsto_zero
#print axioms
  CMVRelaxation.SmoothSequence.exists_two_verticalSeamLengths_tendsto_zero
#print axioms CMVRelaxation.smoothCostOn_spliceIn_eq_inside
#print axioms CMVRelaxation.smoothCostOn_spliceIn_eq_outside
#print axioms
  CMVRelaxation.IsSmoothDomain.spliceIn_of_agree_near_frontier
#print axioms CMVRelaxation.compl_interior_subset_interior_compl_union
#print axioms
  CMVRelaxation.smoothCostOn_spliceIn_eq_compl_interior_of_agree_near_frontier
#print axioms
  CMVRelaxation.smoothCost_spliceIn_eq_inside_add_outside
#print axioms
  CMVRelaxation.smoothCost_spliceIn_add_le_of_agree_near_frontier
#print axioms CMVRelaxation.characteristicDistance_spliceIn_le
#print axioms
  CMVRelaxation.tendsto_characteristicDistance_spliceIn_zero
#print axioms
  CMVRelaxation.relaxedPerimeter_add_le_of_smoothSequence_transfer
#print axioms
  CMVRelaxation.SmoothSequence.cost_add_le_of_pointwise_add_allowance
#print axioms
  CMVRelaxation.SmoothSequence.exists_graphTangentPatch_payoff_le_liminf_smoothCostOn
#print axioms
  CMVRelaxation.SmoothSequence.exists_actualTwoPatch_tangent_payoffs_le_liminf
#print axioms
  CMVRelaxation.relaxedPerimeter_add_le_of_termwise_smoothSequence_transfer
#print axioms CMVRelaxation.exists_midpoint_sum_add_ge_intervalIntegral
#print axioms CMVRelaxation.abs_graphTangentFrame_fst_sub_le_div_speed
#print axioms CMVRelaxation.abs_supergraphTangentFrame_fst_sub_le_div_speed
#print axioms CMVRelaxation.tangentBox_residual_lt_of_bound_div_speed
#print axioms
  CMVTwoPatchGraphVariation.GraphPatch.tangentProjectionBox_subset_graphTube_div_speed
#print axioms
  CMVTwoPatchGraphVariation.GraphPatch.tangentProjectionBox_subset_fst_Ioo
#print axioms
  CMVTwoPatchGraphVariation.GraphPatch.tangentRigidProjectionPatch_window
#print axioms
  CMVTwoPatchGraphVariation.GraphPatch.tangentRigidProjectionPatch_payoff
#print axioms
  CMVTwoPatchGraphVariation.GraphPatch.exists_pairwiseDisjoint_tangentPatches_payoff_ge
#print axioms
  CMVTwoPatchGraphVariation.GraphPatch.weightedGraphLength_le_liminf_smoothCostOn_add
#print axioms CMVRelaxation.SmoothSequence.reindex
#print axioms CMVRelaxation.SmoothSequence.convergesTo_reindex
#print axioms
  CMVRelaxation.SmoothSequence.cost_reindex_eq_of_tendsto
#print axioms
  CMVRelaxation.SmoothSequence.exists_finiteCost_reindex_of_cost_lt_top
#print axioms
  CMVRelaxation.exists_nearMinimizing_finiteCost_smoothSequence
#print axioms
  CMVRelaxation.RigidProjectionPatch.finset_sum_payoff_add_compl_le_smoothCost_add_error
#print axioms
  CMVRelaxation.SmoothSequence.cost_add_finset_payoff_le_of_outside_repair
#print axioms CMVRelaxation.spliceCutTrace
#print axioms CMVRelaxation.frontier_spliceIn_subset_piecewise
#print axioms
  CMVRelaxation.frontierMeasure_ne_top_of_smoothCostOn_ne_top
#print axioms
  CMVRelaxation.exists_verticalSliceVolume_le_average_avoiding
#print axioms
  CMVRelaxation.countable_pos_frontierMeasure_verticalLine_inter
#print axioms
  CMVRelaxation.exists_verticalSliceVolume_le_average_frontier_null
#print axioms
  CMVRelaxation.exists_horizontalSliceVolume_le_average_avoiding
#print axioms
  CMVRelaxation.countable_pos_frontierMeasure_horizontalLine_inter
#print axioms
  CMVRelaxation.exists_horizontalSliceVolume_le_average_frontier_null
#print axioms
  CMVRelaxation.weightedTraceCost_verticalCutInputsOn_le_of_frontier_null
#print axioms
  CMVRelaxation.exists_verticalCutInputsOn_le_average
#print axioms
  CMVRelaxation.weightedTraceCost_horizontalCutInputsOn_le_of_frontier_null
#print axioms
  CMVRelaxation.exists_horizontalCutInputsOn_le_average
#print axioms
  CMVRelaxation.exists_closedCutRectangle_spliceCutTrace_le_averages
#print axioms CMVRelaxation.smoothCost_spliceIn_le_piecewise
#print axioms
  CMVRelaxation.smoothCost_spliceIn_le_outside_add_inside_add_cutTrace
#print axioms CMVRelaxation.smoothCostOn_mono
#print axioms
  CMVRelaxation.exists_closedCutRectangle_spliceCutTrace_le_collar_averages
#print axioms
  CMVRelaxation.tendsto_volume_inter_symmDiff_zero_of_characteristicDistance
#print axioms
  CMVRelaxation.tendsto_volume_inter_symmDiff_zero_of_local_agreement
#print axioms
  CMVRelaxation.exists_closedCutRectangle_spliceCutTrace_tendsto_zero
#print axioms
  CMVRelaxation.exists_closedCutRectangle_spliceCutTrace_tendsto_zero_of_core_support
#print axioms
  CMVRelaxation.IsSmoothDomain.exists_finite_regular_boundary_cover
#print axioms
  CMVRelaxation.exists_verticalSliceVolume_le_average_avoiding_null
#print axioms
  CMVRelaxation.exists_horizontalSliceVolume_le_average_avoiding_null
#print axioms CMVRelaxation.volume_image_critical_eq_zero
#print axioms CMVRelaxation.smoothCost_sublevel_le_outside_add_zeroSet
#print axioms CMVRelaxation.boundedBadJet
#print axioms CMVRelaxation.boundedPerturb
#print axioms CMVRelaxation.contDiff_boundedBadJet
#print axioms CMVRelaxation.dense_regularBoundedParameters
#print axioms CMVRelaxation.boundedPerturb_regular
#print axioms CMVRelaxation.abs_boundedPerturb_sub_le
#print axioms CMVRelaxation.isSmoothDomain_sublevel_of_regular
#print axioms CMVRelaxation.exists_smoothDomain_boundedPerturb
#print axioms CMVRelaxation.exists_contDiff_cutoff_one_nhds_closed
#print axioms CMVRelaxation.localizedBoundedPerturb
#print axioms CMVRelaxation.contDiff_boundedPerturb
#print axioms CMVRelaxation.contDiff_localizedBoundedPerturb
#print axioms CMVRelaxation.abs_localizedBoundedPerturb_sub_le
#print axioms
  CMVRelaxation.exists_smoothDomain_localizedBoundedPerturb
#print axioms CMVRelaxation.exists_localizedSmoothSequence_sublevel
#print axioms CMVRelaxation.finite_compact_fiber_of_hasDerivAt_ne
#print axioms
  CMVRelaxation.volume_setOf_not_finite_compact_fiber_eq_zero
#print axioms CMVRelaxation.smoothCost_localizedSublevel_le
#print axioms CMVRelaxation.complexGraph
#print axioms CMVRelaxation.hasDerivAt_complexGraph
#print axioms CMVRelaxation.norm_complexGraph_deriv
#print axioms CMVRelaxation.lipschitzOnWith_complexGraph_Icc
#print axioms CMVRelaxation.euclideanGraph
#print axioms CMVRelaxation.euclideanGraph_eq
#print axioms CMVRelaxation.lipschitzOnWith_euclideanGraph_Icc
#print axioms CMVRelaxation.hausdorffMeasure_euclideanGraph_Icc_le
#print axioms CMVRelaxation.weightedTraceCost_iUnion_fin_le
#print axioms
  CMVRelaxation.tendsto_weightedTraceCost_iUnion_fin_zero
#print axioms CMVRelaxation.weightedTraceCost_graph_Icc_le
#print axioms
  CMVRelaxation.tendsto_weightedTraceCost_graph_Icc_zero
#print axioms
  CMVRelaxation.smoothCost_spliceIn_occupiedGraphDomain_le
#print axioms
  CMVRelaxation.smoothCost_spliceIn_occupiedGraphDomain_le_of_graph_bound
#print axioms
  CMVRelaxation.Icc_subset_singleton_union_iUnion_adjacent
#print axioms
  CMVRelaxation.hausdorffMeasure_euclideanGraph_Icc_le_intervalIntegral_add
#print axioms
  CMVRelaxation.hausdorffMeasure_euclideanGraph_Icc_le_intervalIntegral
#print axioms
  CMVRelaxation.weightedTraceCost_graph_Icc_le_intervalIntegral
#print axioms
  CMVRelaxation.weightedTraceCost_variedGraph_Icc_le_weightedGraphLength
#print axioms
  CMVRelaxation.smoothCost_spliceIn_variedGraph_le_weightedGraphLength
#print axioms
  CMVRelaxation.exists_smoothGraph_splice_cost_le_weightedGraphLength_add
#print axioms
  CMVRelaxation.weightedTraceCost_union_iUnion_graph_Icc_le_intervalIntegrals
#print axioms
  CMVRelaxation.eq_zero_of_mem_frontier_lt_of_continuousAt
#print axioms CMVRelaxation.IsVerticalRegularBoundaryValue
#print axioms CMVRelaxation.IsHorizontalRegularBoundaryValue
#print axioms CMVRelaxation.IsVerticalTransverseCut
#print axioms CMVRelaxation.IsHorizontalTransverseCut
#print axioms
  CMVRelaxation.IsVerticalRegularBoundaryValue.isVerticalTransverseCut
#print axioms
  CMVRelaxation.IsHorizontalRegularBoundaryValue.isHorizontalTransverseCut
#print axioms
  CMVRelaxation.finite_frontier_inter_compact_verticalLine_of_transverse
#print axioms
  CMVRelaxation.finite_frontier_inter_compact_horizontalLine_of_transverse
#print axioms CMVRelaxation.badVerticalCuts
#print axioms CMVRelaxation.badHorizontalCuts
#print axioms
  CMVRelaxation.exists_verticalSliceVolume_le_average_frontier_null_finite
#print axioms
  CMVRelaxation.exists_horizontalSliceVolume_le_average_frontier_null_finite
#print axioms
  CMVRelaxation.exists_verticalSliceVolume_le_average_regular_fibers_avoiding
#print axioms
  CMVRelaxation.exists_horizontalSliceVolume_le_average_regular_fibers_avoiding
#print axioms
  CMVRelaxation.exists_verticalSliceVolume_le_average_frontier_null_regular_finite
#print axioms
  CMVRelaxation.exists_horizontalSliceVolume_le_average_frontier_null_regular_finite
#print axioms
  CMVRelaxation.exists_horizontalSliceVolume_le_average_frontier_null_regular_finite_avoiding
#print axioms
  CMVTwoPatchGraphVariation.GraphPatch.isVerticalRegularBoundaryValue_occupiedGraphDomain
#print axioms
  CMVTwoPatchGraphVariation.GraphPatch.isHorizontalRegularBoundaryValue_occupiedGraphDomain
#print axioms
  CMVTwoPatchGraphVariation.GraphPatch.volume_setOf_not_isHorizontalRegularBoundaryValue_occupiedGraphDomain
#print axioms
  CMVTwoPatchGraphVariation.GraphPatch.volume_setOf_not_isVerticalRegularBoundaryValue_occupiedGraphDomain
#print axioms CMVRelaxation.isCompact_closedCutRectangle
#print axioms
  CMVRelaxation.exists_closedCutRectangle_regular_finite_spliceCutTrace_le_collar_averages
#print axioms CMVRelaxation.IsRegularFiniteVerticalSpliceCut
#print axioms CMVRelaxation.IsRegularFiniteHorizontalSpliceCut
#print axioms
  CMVTwoPatchGraphVariation.GraphPatch.exists_regularFinite_closedCutRectangle_spliceCutTrace_le_collar_averages_against
#print axioms
  CMVTwoPatchGraphVariation.GraphPatch.exists_regularFinite_closedCutRectangle_spliceCutTrace_tendsto_zero_against
#print axioms
  CMVRelaxation.IsSmoothDomain.volume_setOf_not_isVerticalRegularBoundaryValue_eq_zero
#print axioms
  CMVRelaxation.IsSmoothDomain.volume_setOf_not_isHorizontalRegularBoundaryValue_eq_zero
#print axioms
  CMVTwoPatchGraphVariation.GraphPatch.exists_regularFinite_spliceCuts_le_collar_averages_against
#print axioms
  CMVTwoPatchGraphVariation.GraphPatch.exists_regularFinite_spliceCuts_tendsto_zero_against
#print axioms
  CMVRelaxation.frontierMeasure_ne_top_of_smoothCost_ne_top
#print axioms
  CMVTwoPatchGraphVariation.GraphPatch.frontierMeasure_occupiedGraphDomain_closedCutRectangle_ne_top
#print axioms
  CMVTwoPatchGraphVariation.GraphPatch.tendsto_volume_inter_occupiedGraphDomain_symmDiff_zero_of_uniform
#print axioms
  CMVTwoPatchGraphVariation.GraphPatch.exists_finiteCost_regularFinite_spliceCuts_tendsto_zero_against
#print axioms
  CMVTwoPatchGraphVariation.GraphPatch.exists_common_smoothGraphs_finiteCost_regularFinite_spliceCuts
#print axioms
  CMVRelaxation.weightedTraceCost_graph_Icc_le_intervalIntegral_of_zone
#print axioms
  CMVTwoPatchGraphVariation.GraphPatch.exists_finiteCost_regularFinite_rawSplices
#print axioms CMVRelaxation.spliceIn_subset_closure_openSpliceIn
#print axioms CMVRelaxation.frontier_openSpliceIn_eq_frontier_spliceIn
#print axioms CMVRelaxation.openSpliceIn_ae_eq_spliceIn
#print axioms CMVRelaxation.characteristicDistance_openSpliceIn_eq_spliceIn
#print axioms CMVRelaxation.smoothCost_openSpliceIn_eq_smoothCost_spliceIn
#print axioms CMVRelaxation.closure_interior_closedCutRectangle
#print axioms CMVRelaxation.volume_frontier_closedCutRectangle
#print axioms
  CMVRelaxation.smoothCost_openSpliceIn_le_outside_add_inside_add_cutTrace
#print axioms
  CMVRelaxation.FiniteJunctionRepair.weightedTraceCost_eq_euclideanWeightedTraceMeasure
#print axioms
  CMVRelaxation.FiniteJunctionRepair.tendsto_weightedTraceCost_inter_junctionBall_zero
#print axioms
  CMVRelaxation.FiniteJunctionRepair.tendsto_volume_neighborhood_zero
#print axioms
  CMVRelaxation.FiniteJunctionRepair.tendsto_weightedTraceCost_inter_neighborhood_zero
#print axioms
  CMVRelaxation.FiniteJunctionRepair.exists_approximantDependent_neighborhoods
#print axioms
  CMVRelaxation.FiniteJunctionRepair.eventually_neighborhood_subset_open
#print axioms
  CMVRelaxation.FiniteJunctionRepair.exists_approximantDependent_neighborhoods_inside
#print axioms
  CMVRelaxation.FiniteJunctionRepair.smoothCost_le_outside_add_auxiliary_of_frontier_subset
#print axioms
  CMVRelaxation.FiniteJunctionRepair.eventually_smoothCost_ne_top_of_outside_add_seam
#print axioms
  CMVRelaxation.FiniteJunctionRepair.SmoothSequence.convergesTo_of_vanishing_modification
#print axioms
  CMVRelaxation.FiniteJunctionRepair.tendsto_weightedTraceCost_of_global_auxiliaryLength_zero
#print axioms
  CMVRelaxation.FiniteJunctionRepair.finite_spliceJunctionSet
#print axioms
  CMVRelaxation.FiniteJunctionRepair.finite_spliceJunctionSet_of_regularFiniteCuts
#print axioms
  CMVRelaxation.FiniteJunctionRepair.finite_spliceJunctionSet_of_selected_regularFinite_closedCutRectangle
#print axioms
  CMVRelaxation.FiniteJunctionRepair.exists_selected_regularFinite_rawSplice_repairScales
#print axioms
  CMVRelaxation.FiniteJunctionRepair.exists_local_halfplane_models_closedCutRectangle
#print axioms
  CMVRelaxation.FiniteJunctionRepair.openSpliceIn_locally_smooth_away_from_spliceJunctionSet
#print axioms
  CMVRelaxation.FiniteJunctionRepair.spliceJunctionSet_subset_frontier_closedCutRectangle
#print axioms
  CMVRelaxation.FiniteJunctionRepair.openSpliceIn_locally_smooth_outside_junctionNeighborhood
#print axioms
  CMVRelaxation.FiniteJunctionRepair.selectedSpliceJunctions_subset_compl_of_core
#print axioms
  CMVRelaxation.FiniteJunctionRepair.exists_selected_regularFinite_rawSplice_repairScales_avoiding_core
#print axioms
  CMVRelaxation.FiniteJunctionRepair.hausdorffMeasure_sphere_le
#print axioms
  CMVRelaxation.FiniteJunctionRepair.euclidean_image_junctionSphere
#print axioms
  CMVRelaxation.FiniteJunctionRepair.junctionSphere_subset_junctionBall
#print axioms
  CMVRelaxation.FiniteJunctionRepair.junctionSpheres_subset_neighborhood
#print axioms
  CMVRelaxation.FiniteJunctionRepair.weightedTraceCost_junctionSphere_le
#print axioms
  CMVRelaxation.FiniteJunctionRepair.weightedTraceCost_junctionSpheres_le_budget
#print axioms
  CMVRelaxation.FiniteJunctionRepair.tendsto_junctionSphereCostBudget_zero
#print axioms
  CMVRelaxation.FiniteJunctionRepair.tendsto_weightedTraceCost_junctionSpheres_zero_of_budget
#print axioms
  CMVRelaxation.FiniteJunctionRepair.exists_approximantDependent_neighborhoods_inside_with_sphericalBudget
#print axioms
  CMVRelaxation.FiniteJunctionRepair.exists_repairedSequence_cost_add_finset_payoff_le
#print axioms
  CMVRelaxation.exists_contDiff_infty_implicitGraph_of_contDiffOn
#print axioms
  CMVRelaxation.local_oriented_smooth_graph_of_vertical_regular
#print axioms
  CMVRelaxation.local_oriented_smooth_graph_of_horizontal_regular
#print axioms
  CMVRelaxation.FiniteJunctionRepair.frontier_junctionBall_subset_junctionSphere
#print axioms
  CMVRelaxation.FiniteJunctionRepair.frontier_neighborhood_subset_junctionSpheres
#print axioms
  CMVRelaxation.FiniteJunctionRepair.eventually_pairwiseDisjoint_junctionBalls
#print axioms
  CMVRelaxation.FiniteJunctionRepair.exists_repairedSequence_cost_add_finset_payoff_le_of_spherical_frontier
#print axioms
  CMVRelaxation.FiniteJunctionRepair.exists_vanishing_smoothVerticalGraphSwitchRepair
#print axioms
  CMVRelaxation.FiniteJunctionRepair.exists_smoothVerticalGraphSwitchRepair
#print axioms CMVRelaxation.IsSmoothDomain.coordinateSwap_preimage
#print axioms
  CMVRelaxation.FiniteJunctionRepair.openSpliceIn_occupiedGraphDomains_rightHalfspace_eq_filledVerticalGraphSwitch
#print axioms
  CMVRelaxation.FiniteJunctionRepair.occupiedGraphDomain_connectGraphs_symmDiff_filledSwitch_subset_closedGraphBand
#print axioms
  CMVRelaxation.FiniteJunctionRepair.eventually_symmetricConnector_closedGraphBand_subset_junctionBall
#print axioms
  CMVRelaxation.FiniteJunctionRepair.horizontalOccupiedGraphDomain_connectGraphs_symmDiff_filledSwitch_subset
#print axioms
  CMVRelaxation.FiniteJunctionRepair.eventually_symmetricHorizontalConnector_closedGraphBand_subset_junctionBall
#print axioms
  CMVRelaxation.FiniteJunctionRepair.exists_vanishing_smoothHorizontalGraphSwitchRepair
#print axioms
  CMVRelaxation.FiniteJunctionRepair.exists_smoothHorizontalGraphSwitchRepair
#print axioms
  CMVRelaxation.FiniteJunctionRepair.roundedOppositeCrossingValue_regular
#print axioms
  CMVRelaxation.FiniteJunctionRepair.isSmoothDomain_roundedOppositeCrossing
#print axioms
  CMVRelaxation.FiniteJunctionRepair.openSpliceIn_oppositeOccupiedGraphDomains_rightHalfspace_eq
#print axioms
  CMVRelaxation.FiniteJunctionRepair.filledOppositeVerticalGraphSwitch_eq_crossingSublevel
#print axioms
  CMVRelaxation.FiniteJunctionRepair.roundedOppositeCrossing_symmDiff_crossing_subset_core
#print axioms
  CMVRelaxation.FiniteJunctionRepair.frontier_roundedOppositeCrossing_subset_trace_union
#print axioms
  CMVRelaxation.FiniteJunctionRepair.weightedTraceCost_frontier_roundedOppositeCrossing_inter_core_le
#print axioms
  CMVRelaxation.FiniteJunctionRepair.roundedOppositeCrossing_symmDiff_filledSwitch_subset
#print axioms
  CMVRelaxation.FiniteJunctionRepair.weightedTraceCost_roundedOppositeCrossing_alteredFrontier_le
#print axioms
  CMVRelaxation.FiniteJunctionRepair.tendsto_weightedTraceCost_roundedOppositeCrossing_alteredFrontier_zero
#print axioms
  CMVRelaxation.FiniteJunctionRepair.exists_vanishing_smoothOppositeVerticalGraphSwitchRepair
#print axioms
  CMVRelaxation.FiniteJunctionRepair.exists_smoothOppositeVerticalOpenSpliceRepair
#print axioms
  CMVRelaxation.FiniteJunctionRepair.planeCoordinateSwap_preimage_openSpliceIn
#print axioms
  CMVRelaxation.FiniteJunctionRepair.openSpliceIn_horizontalOccupiedGraphDomains_upperHalfspace_eq
#print axioms
  CMVRelaxation.FiniteJunctionRepair.hausdorffMeasure_le_weightedTraceCost
#print axioms
  CMVRelaxation.FiniteJunctionRepair.weightedTraceCost_planeCoordinateSwap_preimage_le
#print axioms
  CMVRelaxation.FiniteJunctionRepair.planeCoordinateSwap_preimage_junctionBall
#print axioms
  CMVRelaxation.FiniteJunctionRepair.openSpliceIn_oppositeHorizontalOccupiedGraphDomains_upperHalfspace_eq
#print axioms
  CMVRelaxation.FiniteJunctionRepair.exists_vanishing_smoothOppositeHorizontalGraphSwitchRepair
#print axioms
  CMVRelaxation.FiniteJunctionRepair.exists_smoothHorizontalOpenSpliceRepair
#print axioms
  CMVRelaxation.FiniteJunctionRepair.exists_smoothOppositeHorizontalGraphSwitchRepair
#print axioms
  CMVRelaxation.FiniteJunctionRepair.exists_smoothOppositeHorizontalOpenSpliceRepair
#print axioms
  CMVRelaxation.FiniteJunctionRepair.selectedRawSplice_corner_mem_cutTrace_and_local_cases
#print axioms
  CMVRelaxation.FiniteJunctionRepair.openCornerSector_below_mem_iff
#print axioms
  CMVRelaxation.FiniteJunctionRepair.openCornerSector_above_mem_iff
#print axioms
  CMVRelaxation.FiniteJunctionRepair.isSmoothDomain_roundedCorner
#print axioms
  CMVRelaxation.FiniteJunctionRepair.roundedCorner_symmDiff_openCornerSector_subset_core
#print axioms
  CMVRelaxation.FiniteJunctionRepair.weightedTraceCost_frontier_roundedCorner_inter_core_le
#print axioms
  CMVRelaxation.FiniteJunctionRepair.exists_vanishing_smoothCornerSectorRepair
#print axioms
  CMVRelaxation.FiniteJunctionRepair.exists_smoothCornerSectorRepair
#print axioms
  CMVRelaxation.FiniteJunctionRepair.exists_orientedCorner_local_models_closedCutRectangle
#print axioms
  CMVRelaxation.FiniteJunctionRepair.exists_selectedRawSplice_cleanCorner_local_model
#print axioms
  CMVRelaxation.FiniteJunctionRepair.exists_junctionBall_subset_open
#print axioms
  CMVRelaxation.FiniteJunctionRepair.exists_smoothSelectedRawSpliceCleanCornerRepair
#print axioms
  CMVRelaxation.FiniteJunctionRepair.isClosed_roundedCornerCore
#print axioms
  CMVRelaxation.FiniteJunctionRepair.junctionSphere_disjoint_half_junctionBall
#print axioms
  CMVRelaxation.FiniteJunctionRepair.exists_openGraftedSelectedRawSpliceCleanCornerRepair
namespace CMVRelaxation.FiniteJunctionRepair
#print axioms selectedRawSplice_all_corners_have_openGraftedRepair_of_cornerFreeCuts
#print axioms SpliceGraphOccupiedSide
#print axioms HasOrientedSmoothBoundaryGraphGermOnSide
#print axioms
  HasOrientedSmoothBoundaryGraphGermOnSide.exists_vertical_graphDomain_germ
#print axioms
  HasOrientedSmoothBoundaryGraphGermOnSide.exists_horizontal_graphDomain_germ
#print axioms
  HasOrientedSmoothBoundaryGraphGermOnSide.exists_eventually_occupiedGraphDomain
#print axioms HasOrientedSmoothBoundaryGraphGerm
#print axioms openSpliceIn_swap_compl
#print axioms
  HasOrientedSmoothBoundaryGraphGermOnSide.exists_first_openSplice_local_sector
#print axioms
  HasOrientedSmoothBoundaryGraphGermOnSide.exists_second_openSplice_local_sector
#print axioms SelectedSpliceInputGermCase
#print axioms OpenSpliceNoncornerRegularGermData
#print axioms exists_openSplice_noncorner_regularGermData
#print axioms exists_selectedRawSplice_noncorner_regularGermData
end CMVRelaxation.FiniteJunctionRepair
