import CMVOrientedLoopLocalization

open CMVBoundaryLocalAtlas.SmoothGraphAtlas
open CMVRelaxation
open CMVRelaxation.FiniteJunctionRepair

#print axioms HasOrientedSmoothBoundaryGraphGermOnSide.congr_nhds
#print axioms PointwiseHalfSpaceChart.nonempty_of_local_smooth_model
#print axioms orientedCornerCoordinate
#print axioms signedCoordinateOccupied
#print axioms graphCutFrame
#print axioms PointwiseHalfSpaceChart.nonempty_of_orientedGraphCut
#print axioms nonempty_pointwiseHalfSpaceChart_openSpliceIn_empty_cleanCorner
#print axioms nonempty_pointwiseHalfSpaceChart_openSpliceIn_empty_noncornerJunction
#print axioms boundaryHalfSpaceAtlas_openSpliceIn_empty_of_regularFiniteCuts
#print axioms FiniteBoundaryTopology
#print axioms finiteBoundaryTopologyOfAtlas
#print axioms
  CMVBoundaryLocalAtlas.BoundaryHalfSpaceAtlas.FiniteChartCutSystem.additionalCutPoint_mem_cutPoints
#print axioms
  CMVBoundaryLocalAtlas.BoundaryHalfSpaceAtlas.finiteChartCutSystemIncluding
#print axioms FinitePiecewiseRegularBoundaryTopology
#print axioms FiniteJunctionBoundaryData
#print axioms finiteJunctionBoundaryData_openSpliceIn
#print axioms
  finiteJunctionBoundaryData_openSpliceIn_exceptionalPoints
#print axioms finitePiecewiseRegularBoundaryTopologyOfData
#print axioms
  finitePiecewiseRegularBoundaryTopologyOfData_exceptionalPoints
#print axioms
  FinitePiecewiseRegularBoundaryTopology.exceptionalPoints_subset_cutPoints
#print axioms
  FinitePiecewiseRegularBoundaryTopology.smooth_away_exceptionalPoints
#print axioms
  FinitePiecewiseRegularBoundaryTopology.smooth_away_cutPoints
#print axioms finitePiecewiseRegularBoundaryTopologyOfAtlas
#print axioms
  FinitePiecewiseRegularBoundaryTopology.smooth_finiteArcInterior
#print axioms CMVRelaxation.HasFiniteJunctionBoundaryAtlas
#print axioms CMVRelaxation.hasFiniteJunctionBoundaryAtlas_openSpliceIn
#print axioms CMVRelaxation.isSmoothDomain_empty
#print axioms CMVRelaxation.openSpliceIn_empty_eq_inter_interior
#print axioms CMVRelaxation.exists_nonneg_strict_coordinate_bound
#print axioms CMVRelaxation.SmoothSequence.exists_strictMono_finiteCost_reindex_of_cost_lt_top
#print axioms CMVRelaxation.HasOpenRectangularLocalization
#print axioms CMVRelaxation.exists_regularFinite_closedCutRectangle_spliceCutTrace_tendsto_zero
#print axioms CMVRelaxation.SmoothSequence.exists_open_rectangular_localization
#print axioms CMVRelaxation.HasOpenRectangularLocalization.exists_finiteJunctionBoundaryAtlases
#print axioms HasOpenRectangularLocalization.exists_boundaryHalfSpaceAtlases
#print axioms HasOpenRectangularLocalization.exists_finiteBoundaryTopologies
#print axioms
  HasOpenRectangularLocalization.exists_finitePiecewiseRegularBoundaryTopologies
#print axioms
  HasOpenRectangularLocalization.exists_actualJunctionOrientedTopologies
#print axioms
  HasOpenRectangularLocalization.exists_occupiedLeftArcBranchAssignments
#print axioms
  HasOpenRectangularLocalization.exists_transverseEndpointTraces
#print axioms HasOpenRectangularLocalization.exists_cleanCornerCutTraces
#print axioms HasOpenRectangularLocalization.exists_finiteBoundaryIncidences
#print axioms HasOpenRectangularLocalization.exists_finiteBoundaryCyclicTraversals
#print axioms HasOpenRectangularLocalization.exists_finiteBoundaryGeometricTraversals
#print axioms HasFiniteBoundaryClosedWalkPaths
#print axioms
  HasOpenRectangularLocalization.exists_finiteBoundaryClosedWalkPaths
