import CMVOrientedLoopEndpointOrientation

open CMVBoundaryLocalAtlas
open CMVRelaxation
open CMVRelaxation.FiniteJunctionRepair

#print axioms
  BoundaryHalfSpaceAtlas.FiniteChartCutSystem.finiteArcPointLRLocalPoint
#print axioms
  BoundaryHalfSpaceAtlas.FiniteChartCutSystem.finiteArcPathLR_chartCoordinate
#print axioms
  BoundaryHalfSpaceAtlas.FiniteChartCutSystem.continuous_finiteArcPointLR
#print axioms
  BoundaryHalfSpaceAtlas.FiniteChartCutSystem.isClosedEmbedding_finiteArcPointLR
#print axioms
  BoundaryHalfSpaceAtlas.FiniteChartCutSystem.finiteArcPointLRHomeomorph
#print axioms
  BoundaryHalfSpaceAtlas.FiniteChartCutSystem.finiteArcPointLRHomeomorph_apply
#print axioms
  BoundaryHalfSpaceAtlas.FiniteChartCutSystem.finiteArcPointLRHomeomorph_symm_apply
#print axioms
  BoundaryHalfSpaceAtlas.FiniteChartCutSystem.finiteArcPointLRHomeomorph_symm_leftEndpoint
#print axioms
  BoundaryHalfSpaceAtlas.FiniteChartCutSystem.finiteArcPointLRHomeomorph_symm_rightEndpoint
#print axioms
  BoundaryHalfSpaceAtlas.FiniteChartCutSystem.finiteArcPointLRHomeomorph_symm_mem_openUnitInterval_iff
#print axioms
  BoundaryHalfSpaceAtlas.FiniteChartCutSystem.finiteArcPointLRHomeomorph_symm_halfEdgeClosurePoint
#print axioms
  OccupiedLeftArcBranchAssignment.strictMonotone_finiteArcInverse_from_halfEdge
#print axioms
  OccupiedLeftArcBranchAssignment.strictMonotone_finiteArcInverse_to_halfEdge
#print axioms
  OccupiedLeftArcBranchAssignment.representativeOrientationPointsAway_of_endpointArcContinuation
#print axioms
  OccupiedLeftArcBranchAssignment.representativeOrientationPointsAway_of_endpointArcApproach
#print axioms
  OccupiedLeftArcBranchAssignment.RightSidedEndpointTrace.representativeOrientationPointsAway_eq_true
#print axioms
  OccupiedLeftArcBranchAssignment.LeftSidedEndpointTrace.representativeOrientationPointsAway_eq_false
#print axioms
  BoundaryHalfSpaceAtlas.FiniteChartCutSystem.incidentArcEquivBool_symm_switchHalfEdge
#print axioms
  BoundaryHalfSpaceAtlas.FiniteChartCutSystem.localGermHalfEdge
#print axioms
  BoundaryHalfSpaceAtlas.FiniteChartCutSystem.incidentArcEquivBool_symm_localGermHalfEdge
#print axioms
  BoundaryHalfSpaceAtlas.FiniteChartCutSystem.switchHalfEdge_localGermHalfEdge
#print axioms OccupiedLeftArcBranchAssignment.isSwitchCompatible_of_localGermParity
#print axioms OccupiedLeftArcBranchAssignment.HasUniqueOccupiedLeftOutgoingAtCutPoints
#print axioms
  OccupiedLeftArcBranchAssignment.isSwitchCompatible_of_uniqueOccupiedLeftOutgoingAtCutPoints
#print axioms OccupiedLeftArcBranchAssignment.isSwitchCompatible_of_localGermPair
#print axioms OccupiedLeftArcBranchAssignment.isSwitchCompatible_iff_localGermPair
#print axioms OccupiedLeftArcBranchAssignment.localGermPair_of_localOutgoingGerm
#print axioms OccupiedLeftArcBranchAssignment.isSwitchCompatible_of_localOutgoingGerm
#print axioms
  OccupiedLeftArcBranchAssignment.isSwitchCompatible_of_oneSidedEndpointTraces
#print axioms
  OccupiedLeftArcBranchAssignment.isSwitchCompatible_of_endpointArcTraces
#print axioms
  OccupiedLeftArcBranchAssignment.isSwitchCompatible_of_ordinaryCutPointTraces
#print axioms OccupiedLeftArcBranchAssignment.occupiedLeftBoundaryLoopHalfEdge
#print axioms
  OccupiedLeftArcBranchAssignment.boundaryLoopIndexOfHalfEdge_occupiedLeftBoundaryLoopHalfEdge
#print axioms
  OccupiedLeftArcBranchAssignment.representativeOrientationPointsAway_occupiedLeftBoundaryLoopHalfEdge
#print axioms
  OccupiedLeftArcBranchAssignment.representativeOrientationPointsAway_iterate_occupiedLeftBoundaryLoopHalfEdge
#print axioms
  OccupiedLeftArcBranchAssignment.switch_iterate_occupiedLeftBoundaryLoopHalfEdge_eq_oriented
#print axioms
  OccupiedLeftArcBranchAssignment.occupiedLeftBoundaryGeometricWalkLoop
#print axioms
  OccupiedLeftArcBranchAssignment.existsUnique_lt_occupiedLeftPeriod_traversedArc_eq
#print axioms
  OccupiedLeftArcBranchAssignment.occupiedLeftBoundaryGeometricWalkLoop_path_range_eq_iUnion_arcs
#print axioms
  OccupiedLeftArcBranchAssignment.occupiedLeftBoundaryGeometricWalkLoop_path_range_eq
#print axioms
  OccupiedLeftArcBranchAssignment.occupiedLeftBoundaryGeometricWalkLoop_traverses_orientedHalfEdge
