import CMVOrientedLoopOrientation

open CMVBoundaryLocalAtlas
open CMVRelaxation
open CMVRelaxation.FiniteJunctionRepair

#print axioms OccupiedLeftRegularTrace.graph_eq_base
#print axioms frontier_orientedGraphDomain
#print axioms OccupiedLeftRegularTrace.frontier_eventually
#print axioms OccupiedLeftRegularTrace.crossAxis_inverse_eventually
#print axioms OccupiedLeftRegularTrace.crossAxis_deriv_mul
#print axioms OccupiedLeftRegularTrace.crossAxis_horizontal_graph_right
#print axioms OccupiedLeftRegularTrace.crossAxis_horizontal_deriv_sign
#print axioms OccupiedLeftRegularTrace.crossAxis_velocity_positive_smul
#print axioms OccupiedLeftRegularTrace.eventuallyEq_graph
#print axioms OccupiedLeftRegularTrace.velocity_eq
#print axioms OccupiedLeftRegularTrace.side_eq
#print axioms OccupiedLeftRegularTrace.velocity_eq_of_same_axis
#print axioms OccupiedLeftRegularTrace.velocity_positive_smul
#print axioms occupiedLeftParameterCLM
#print axioms occupiedLeftTraceParameter
#print axioms continuous_occupiedLeftTraceParameter
#print axioms occupiedLeftTraceParameter_base
#print axioms OccupiedLeftRegularTrace.rebase
#print axioms occupiedLeftGraphTrace_traceParameter_of_mem_frontier
#print axioms OccupiedLeftRegularTrace.transitionParameter
#print axioms OccupiedLeftRegularTrace.transitionParameter_base
#print axioms OccupiedLeftRegularTrace.transitionParameter_contDiff
#print axioms OccupiedLeftRegularTrace.transitionParameter_hasDerivAt
#print axioms OccupiedLeftRegularTrace.transitionParameter_deriv_pos
#print axioms
  OccupiedLeftRegularTrace.exists_radius_strictMonoOn_transitionParameter
#print axioms
  OccupiedLeftRegularTrace.transitionParameter_trace_eventually
#print axioms OccupiedLeftArcBranch
#print axioms OccupiedLeftArcBranch.velocity
#print axioms OccupiedLeftArcBranch.velocity_ne_zero
#print axioms
  FinitePiecewiseRegularBoundaryTopology.arcRepresentative_mem_finiteArcInterior
#print axioms
  FinitePiecewiseRegularBoundaryTopology.exists_occupiedLeftArcBranch
#print axioms OccupiedLeftArcBranchAssignment
#print axioms
  FinitePiecewiseRegularBoundaryTopology.occupiedLeftArcBranchAssignment
#print axioms OccupiedLeftArcBranchAssignment.branch_chart_independent
#print axioms OccupiedLeftArcBranchAssignment.branchAtHalfEdge
#print axioms OccupiedLeftArcBranchAssignment.arcReferenceVelocity
#print axioms OccupiedLeftArcBranchAssignment.branchVelocityAtHalfEdge
#print axioms
  OccupiedLeftArcBranchAssignment.branchAtHalfEdge_crossHalfEdge_velocity
#print axioms OccupiedLeftRegularTrace.trace_mem_model_frontier
#print axioms OccupiedLeftArcCoordinateNeighborhood
#print axioms OccupiedLeftArcCoordinateNeighborhood.point
#print axioms OccupiedLeftArcCoordinateNeighborhood.point_mem_arc
#print axioms OccupiedLeftArcCoordinateNeighborhood.point_mem_chartWindow
#print axioms OccupiedLeftArcCoordinateNeighborhood.localPoint
#print axioms OccupiedLeftArcCoordinateNeighborhood.localPoint_val
#print axioms OccupiedLeftArcCoordinateNeighborhood.coordinate
#print axioms OccupiedLeftArcCoordinateNeighborhood.exists_unitParameter
#print axioms OccupiedLeftArcCoordinateNeighborhood.unitParameter
#print axioms
  OccupiedLeftArcCoordinateNeighborhood.unitParameter_mem_openUnitInterval
#print axioms
  OccupiedLeftArcCoordinateNeighborhood.finiteArcPointLR_unitParameter
#print axioms
  OccupiedLeftArcCoordinateNeighborhood.eq_unitParameter_of_finiteArcPointLR_eq
#print axioms
  OccupiedLeftArcCoordinateNeighborhood.coordinate_eq_affine_unitParameter
#print axioms
  OccupiedLeftArcCoordinateNeighborhood.unitParameter_val_eq_normalizedCoordinate
#print axioms OccupiedLeftArcCoordinateNeighborhood.continuous_point
#print axioms OccupiedLeftArcCoordinateNeighborhood.continuous_localPoint
#print axioms OccupiedLeftArcCoordinateNeighborhood.continuous_coordinate
#print axioms OccupiedLeftArcCoordinateNeighborhood.continuous_unitParameter
#print axioms OccupiedLeftArcCoordinateNeighborhood.injective_coordinate
#print axioms
  OccupiedLeftArcCoordinateNeighborhood.strictMono_or_strictAnti_coordinate
#print axioms
  OccupiedLeftArcCoordinateNeighborhood.strictMono_unitParameter_of_strictMono_coordinate
#print axioms
  OccupiedLeftArcCoordinateNeighborhood.strictAnti_unitParameter_of_strictAnti_coordinate
#print axioms
  OccupiedLeftArcCoordinateNeighborhood.strictMono_or_strictAnti_unitParameter
#print axioms
  OccupiedLeftArcCoordinateNeighborhood.orientation_agrees
#print axioms
  OccupiedLeftArcCoordinateNeighborhood.orientation_agrees_of_common_parameter
#print axioms
  OccupiedLeftArcCoordinateNeighborhood.strictMono_coordinate_iff_unitParameter
#print axioms
  OccupiedLeftArcCoordinateNeighborhood.coordinateIncreases
#print axioms
  OccupiedLeftArcCoordinateNeighborhood.coordinateIncreases_eq
#print axioms
  OccupiedLeftArcCoordinateNeighborhood.coordinateIncreases_eq_of_common_parameter
#print axioms
  FinitePiecewiseRegularBoundaryTopology.exists_occupiedLeftArcCoordinateNeighborhood
#print axioms OccupiedLeftArcBranchAssignment.pointCoordinateNeighborhood
#print axioms OccupiedLeftArcBranchAssignment.pointCoordinateIncreases
#print axioms OccupiedLeftArcBranchAssignment.pointCoordinateIncreases_eq
#print axioms
  OccupiedLeftArcBranchAssignment.pointCoordinateIncreases_isLocallyConstant
#print axioms
  OccupiedLeftArcBranchAssignment.pointCoordinateIncreases_eq_on_arc
#print axioms
  OccupiedLeftArcBranchAssignment.pointCoordinateIncreases_eq_arcCoordinateIncreases
#print axioms
  OccupiedLeftArcBranchAssignment.coordinateNeighborhood_increases_eq_arcCoordinateIncreases
#print axioms
  OccupiedLeftArcBranchAssignment.coordinateNeighborhood_strictMono_unitParameter
#print axioms
  OccupiedLeftArcBranchAssignment.coordinateNeighborhood_strictAnti_unitParameter
#print axioms OccupiedLeftArcBranchAssignment.arcCoordinateNeighborhood
#print axioms OccupiedLeftArcBranchAssignment.arcCoordinateIncreases
#print axioms OccupiedLeftArcBranchAssignment.arcCoordinateIncreases_eq_true
#print axioms OccupiedLeftArcBranchAssignment.arcCoordinateIncreases_eq_false
#print axioms
  OccupiedLeftArcBranchAssignment.arcCoordinateIncreases_eq_true_unitParameter
#print axioms
  OccupiedLeftArcBranchAssignment.arcCoordinateIncreases_eq_false_unitParameter
#print axioms OccupiedLeftArcBranchAssignment.halfEdgeEndpointSide
#print axioms
  OccupiedLeftArcBranchAssignment.halfEdgeEndpointSide_endpointHalfEdge
#print axioms
  OccupiedLeftArcBranchAssignment.halfEdgeEndpointSide_crossHalfEdge
#print axioms
  OccupiedLeftArcBranchAssignment.representativeOrientationPointsAway
#print axioms
  OccupiedLeftArcBranchAssignment.representativeOrientationPointsAway_crossHalfEdge
#print axioms OccupiedLeftArcBranchAssignment.IsSwitchCompatible
#print axioms
  OccupiedLeftArcBranchAssignment.representativeOrientationPointsAway_walkStep
#print axioms
  OccupiedLeftArcBranchAssignment.representativeOrientationPointsAway_iterate_walkStep
#print axioms
  OccupiedLeftArcBranchAssignment.representativeOrientedHalfEdge
#print axioms
  OccupiedLeftArcBranchAssignment.representativeOrientedHalfEdge_arc
#print axioms
  OccupiedLeftArcBranchAssignment.representativeOrientationPointsAway_orientedHalfEdge
#print axioms
  OccupiedLeftArcBranchAssignment.representativeOrientationPointsAway_cross_orientedHalfEdge
#print axioms
  OccupiedLeftArcBranchAssignment.representativeOrientedHalfEdge_unique
#print axioms HasGloballyOrientedOpenArcs
#print axioms
  FinitePiecewiseRegularBoundaryTopology.hasGloballyOrientedOpenArcs
