import CMVPolygonalFiniteFilling

#print axioms CMVPolygonalModTwo.boundaryOne_formalBoundary
#print axioms CMVPolygonalModTwo.formalBoundary_quadrilateralFilling
#print axioms CMVPolygonalModTwo.shared_edge_cancellation
#print axioms CMVPolygonalModTwo.fillingArea_quadrilateralFilling
#print axioms CMVPolygonalModTwo.toGeometric_segment_subdivision
#print axioms CMVPolygonalModTwo.geometricBoundary_polygonBoundary
#print axioms CMVPolygonalModTwo.twoCarrier_add
#print axioms CMVPolygonalModTwo.flatNorm_polygonBoundary_add_le_symmDiff
#print axioms CMVPolygonalModTwo.hausdorffMeasure_euclideanSegment
#print axioms CMVPolygonalModTwo.flatNorm_segment
#print axioms CMVPolygonalModTwo.euclideanEdist_le_formalMass_of_boundary_support
#print axioms CMVPolygonalModTwo.endpointCalibration_le_representativeMassInf
#print axioms CMVPolygonalModTwo.geometricMass_eq_representativeMassInf
#print axioms CMVPolygonalModTwo.formalBoundary_ringFilling
#print axioms CMVPolygonalModTwo.formalBoundary_rectangularAnnulusFilling
#print axioms CMVPolygonalModTwo.volume_rectangularAnnulusCarrier
#print axioms CMVPolygonalModTwo.fillingArea_rectangularAnnulusFilling
#print axioms CMVPolygonalModTwo.flatNorm_rectangularAnnulusBoundary_le_fillingArea
#print axioms CMVPolygonalModTwo.flatNorm_rectangularAnnulusBoundary_le_twelve
#print axioms CMVPolygonalModTwo.hausdorffMeasure_unitSegment
#print axioms CMVPolygonalModTwo.flatNorm_unitSegment
#print axioms CMVPolygonalModTwo.fillingArea_thinRectangleFilling
#print axioms CMVPolygonalModTwo.thinRectangle_flatNorm_tendsto_zero
#print axioms CMVPolygonalModTwo.formalMass_thinRectangleBoundary
#print axioms CMVPolygonalModTwo.formalMass_thinRectangleBoundary_not_tendsto_zero
#print axioms CMVPolygonalModTwo.geometric_add_self_eq_zero
#print axioms CMVPolygonalModTwo.polygonBoundary_collinearTriangle_zero
#print axioms CMVPolygonalModTwo.fillingArea_collinearTriangle_zero
#print axioms CMVPolygonalModTwo.RegularPolygonalRegion.boundary_empty
#print axioms CMVPolygonalModTwo.RegularPolygonalRegion.boundary_xor
#print axioms CMVPolygonalModTwo.RegularPolygonalRegion.flatNorm_boundary_add_le_volume_symmDiff
#print axioms CMVPolygonalModTwo.RegularPolygonalRegion.rectangularAnnulus_carrier
#print axioms CMVPolygonalModTwo.RegularPolygonalRegion.volume_rectangularAnnulus
#print axioms CMVPolygonalModTwo.RegularPolygonalRegion.outerSquare_boundary_add_innerSquare_boundary
#print axioms CMVPolygonalModTwo.RegularPolygonalRegion.flatNorm_rectangularAnnulus_boundary_le_volume
#print axioms CMVPolygonalModTwo.RegularPolygonalRegion.flatNorm_rectangularAnnulus_boundary_le_twelve
#print axioms CMVPolygonalModTwo.hausdorffMeasure_edgeCarrier
#print axioms CMVPolygonalModTwo.hausdorffMeasure_oneCarrier_eq_formalMass
#print axioms CMVPolygonalModTwo.formalMass_splitSegmentChain
#print axioms CMVPolygonalModTwo.RefinesBySubdivision.toGeometric_eq
#print axioms CMVPolygonalModTwo.PartialOverlap.chain_refines_reducedChain
#print axioms CMVPolygonalModTwo.PartialOverlap.toGeometric_chain_eq_reducedChain
#print axioms CMVPolygonalModTwo.PartialOverlap.formalMass_reducedChain
#print axioms CMVPolygonalModTwo.PartialOverlap.geometricMass_chain_le_two
#print axioms CMVPolygonalModTwo.PartialOverlap.reducedChain_isReduced
#print axioms CMVPolygonalModTwo.PartialOverlap.hausdorffMeasure_oneCarrier_reducedChain
#print axioms CMVPolygonalModTwo.NoncollinearCycle.boundaryOne_cycle
#print axioms CMVPolygonalModTwo.NoncollinearCycle.cycle_isReduced
#print axioms CMVPolygonalModTwo.NoncollinearCycle.hausdorffMeasure_oneCarrier_cycle_eq_formalMass
#print axioms CMVPolygonalModTwo.RectangularAnnulus.ringBoundary_isReduced
#print axioms CMVPolygonalModTwo.RectangularAnnulus.hausdorffMeasure_oneCarrier_ringBoundary_eq_formalMass
#print axioms CMVPolygonalModTwo.oneParity_subdivisionGenerator_of_ne
#print axioms CMVPolygonalModTwo.oneParity_subdivisionGenerator_ae
#print axioms CMVPolygonalModTwo.subdivisionSubgroup_le_oneParityAEKernel
#print axioms CMVPolygonalModTwo.oneParity_ae_eq_of_toGeometric_eq
#print axioms CMVPolygonalModTwo.parityCarrier_ae_eq_of_toGeometric_eq
#print axioms CMVPolygonalModTwo.hausdorffMeasure_parityCarrier_le_formalMass
#print axioms CMVPolygonalModTwo.parityCarrier_ae_eq_oneCarrier_of_reduced
#print axioms CMVPolygonalModTwo.hausdorffMeasure_parityCarrier_eq_formalMass_of_reduced
#print axioms CMVPolygonalModTwo.formalMass_eq_representativeMassInf_of_reduced
#print axioms CMVPolygonalModTwo.geometricMass_toGeometric_eq_formalMass_of_reduced
#print axioms CMVPolygonalModTwo.geometricMass_toGeometric_eq_hausdorffMeasure_oneCarrier_of_reduced
#print axioms CMVPolygonalModTwo.reduced_representatives_mass_independent
#print axioms CMVPolygonalModTwo.PartialOverlap.geometricMass_chain_eq_two
#print axioms
  CMVPolygonalModTwo.PartialOverlap.geometricMass_chain_eq_hausdorffMeasure_reducedCarrier
#print axioms
  CMVPolygonalModTwo.NoncollinearCycle.geometricMass_cycle_eq_hausdorffMeasure_oneCarrier
#print axioms
  CMVPolygonalModTwo.RectangularAnnulus.geometricMass_ringBoundary_eq_hausdorffMeasure_oneCarrier
#print axioms CMVPolygonalModTwo.edge_eq_of_vertexAtomic_of_inter_infinite
#print axioms CMVPolygonalModTwo.isReducedRepresentative_of_vertexAtomic
#print axioms CMVPolygonalModTwo.exists_vertexAtomic_refinement
#print axioms CMVPolygonalModTwo.exists_reduced_refinement
#print axioms CMVPolygonalModTwo.exists_reduced_representative
#print axioms
  CMVPolygonalModTwo.exists_reduced_representative_mass_identification
#print axioms CMVPolygonalModTwo.volume_standardTriangle
#print axioms CMVPolygonalModTwo.volume_triangleCarrier
#print axioms CMVPolygonalModTwo.carrierArea_le_fillingArea
#print axioms CMVPolygonalModTwo.fillingCost_eq_carrierArea
#print axioms CMVPolygonalModTwo.geometricMass_add_le
#print axioms CMVPolygonalModTwo.fillingCost_add_le
#print axioms CMVPolygonalModTwo.flatNorm_add_le
#print axioms
  CMVPolygonalModTwo.flatNorm_polygonBoundary_add_eq_zero_of_twoCarrier_ae_eq
#print axioms CMVPolygonalModTwo.polygonBoundary_unitSquare_triangulations
#print axioms CMVPolygonalModTwo.cyclicTriangle_overlap_cancellation
#print axioms CMVPolygonalModTwo.fillingCost_collinearTriangle_zero
#print axioms CMVPolygonalModTwo.fillingCost_rectangularAnnulus_eq_twelve
