import CMVRegularGermExactAreaFrontier

namespace CMVTwoPatchGraphVariation.GraphPatch

#print axioms compensationBump_eq_zero_of_not_mem_supportCore
#print axioms compensationWindow_subset_openGraphTube
#print axioms frontier_compensationWindow_subset_collar
#print axioms carrier_symmDiff_varied_subset_compensationWindow
#print axioms frontier_occupiedGraphDomain_inter_compensationWindow
#print axioms smoothCostOn_occupiedGraphDomain_compensationWindow
#print axioms compensationWindowWeightedGraphLength_sub_eq_weightedGraphLength_sub

end CMVTwoPatchGraphVariation.GraphPatch

namespace CMVRelaxation.RegularTraceCornerComparison
namespace RemoteCompensationPatch

#print axioms extensionCompetitor_inter_compensationCollar_eq
#print axioms exactAreaExtension_eq_spliceIn
#print axioms exactAreaExtension_complete_cost
#print axioms isOpen_exactAreaExtension
#print axioms exactAreaExtension_complete_cost_balance
#print axioms exactAreaExtension_complete_cost_le_add
#print axioms eventually_correctionShift_lt_quarter
#print axioms eventually_exactAreaExtension_complete_cost_le_add_quadratic
#print axioms eventually_exactAreaExtension_complete_cost

end RemoteCompensationPatch

#print axioms not_completeFrontierMinimizing_of_conormal_lt
#print axioms conormal_inner_ge_neg_inv_of_completeFrontier_minimality
end CMVRelaxation.RegularTraceCornerComparison
