import CMVRegularParametricArclength

namespace CMVRelaxation

#print axioms hausdorffMeasure_parametricCurve_Icc_le_intervalIntegral_add
#print axioms hausdorffMeasure_parametricCurve_Icc_le_intervalIntegral
#print axioms intervalIntegral_le_hausdorffMeasure_parametricCurve_Icc
#print axioms hausdorffMeasure_regularParametricCurve_Icc_eq_intervalIntegral_of_speed_pos
#print axioms euclideanParametricSpeed_pos_of_fderiv_ne_zero
#print axioms hausdorffMeasure_regularParametricCurve_Icc_eq_intervalIntegral
#print axioms hausdorffMeasure_injective_regularParametricCurve_Icc_eq_intervalIntegral
#print axioms hausdorffMeasure_regularParametricCurve_Ico_eq_intervalIntegral_of_speed_pos
#print axioms hausdorffMeasure_regularParametricCurve_Ico_eq_intervalIntegral

end CMVRelaxation
