import CMVRelativeParameterSelection
import CMVRelativeLevelTraceAveraging

#print axioms CMVRelaxation.hausdorffMeasure_range_eq_zero_of_finrank_lt
#print axioms CMVRelaxation.hausdorffMeasure_three_range_boundedBadJet_eq_zero
#print axioms CMVRelaxation.ae_not_mem_range_boundedBadJet
#print axioms CMVRelaxation.exists_small_regularBoundedParameter_le_setLAverage
#print axioms CMVRelaxation.norm_fderiv_boundedPerturb_sub_le
#print axioms CMVRelaxation.norm_fderiv_localizedBoundedPerturb_sub_le
#print axioms CMVRelaxation.hasCompactSupport_localizedBoundedPerturb_sub
#print axioms CMVRelaxation.exists_small_regularBoundedPerturb_with_C1_control
#print axioms CMVRelaxation.affineNormalLevelTrace_eq_levelSet
#print axioms CMVRelaxation.affineNormalPhase_regular
#print axioms CMVRelaxation.aemeasurable_weightedTraceCost_affineNormalLevelTrace
#print axioms CMVRelaxation.setLAverage_weightedTraceCost_affineNormalLevelTrace
#print axioms CMVRelaxation.weightedTraceCost_affineNormalLevelTrace_le_intervalIntegral
#print axioms CMVRelaxation.quadraticLevelTrace_curved_witness
#print axioms CMVRelaxation.setLAverage_weightedTraceCost_quadraticLevelTrace
#print axioms CMVRelaxation.weightedTraceCost_quadraticLevelTrace_le
#print axioms CMVRelaxation.exists_small_regularBoundedPerturb_with_quadraticTraceCost
#print axioms
  CMVRelaxation.measurable_weightedTraceCost_parameterZeroTrace_of_finiteCarrier
#print axioms CMVRelaxation.measurable_parameterGraphAtlasSpeedBudget
#print axioms
  CMVRelaxation.weightedTraceCost_parameterGraphAtlasTrace_le_speedBudget
#print axioms
  CMVRelaxation.exists_small_regularBoundedPerturb_with_C1_control_and_graphAtlasCost
#print axioms
  CMVRelaxation.exists_small_regularBoundedPerturb_with_quadraticParameterTraceCost
#print axioms
  CMVRelaxation.exists_small_regularLocalizedBoundedPerturb_with_C1_control
#print axioms
  CMVRelaxation.exists_small_regularLocalizedBoundedPerturb_with_graphAtlasCost
#print axioms
  CMVRelaxation.uniformPartitionChordSum_le_hausdorffMeasure_image_Icc
#print axioms
  CMVRelaxation.hausdorffMeasure_euclideanGraph_Icc_eq_intervalIntegral
#print axioms
  CMVRelaxation.weightedTraceCost_parameterGraphAtlasTrace_eq_speedBudget
#print axioms
  CMVRelaxation.measurable_weightedTraceCost_parameterGraphAtlasTrace
#print axioms
  CMVRelaxation.exists_small_regularLocalizedBoundedPerturb_with_actualGraphAtlasAverage
#print axioms
  CMVRelaxation.weightedTraceCost_quadraticParameterTrace_eq_speedBudget
#print axioms
  CMVRelaxation.measurable_quadraticParameterSpeedBudget
#print axioms
  CMVRelaxation.exists_small_regularBoundedPerturb_with_quadraticParameterTraceAverage
#print axioms
  CMVRelaxation.hausdorffMeasure_euclideanGraph_image_eq_setLIntegral
#print axioms
  CMVRelaxation.hausdorffMeasure_euclideanGraph_inter_eq_setLIntegral
#print axioms
  CMVRelaxation.weightedTraceCost_graph_image_eq_const_mul_setLIntegral
#print axioms
  CMVRelaxation.hausdorffMeasure_euclideanHorizontalGraph_image_eq_setLIntegral
#print axioms
  CMVRelaxation.weightedTraceCost_horizontalGraph_image_eq_const_mul_setLIntegral
#print axioms
  CMVRelaxation.smoothPhaseZeroTrace_eq_regular_union_critical
#print axioms
  CMVRelaxation.iUnion_regularSmoothPhaseExhaustion
#print axioms
  CMVRelaxation.exists_smoothPhaseGraphChart
#print axioms
  CMVRelaxation.exists_finite_smoothPhaseGraphChart_cover
#print axioms
  CMVRelaxation.exists_countable_measurable_disjoint_smoothPhaseGraph_decomposition
#print axioms
  CMVRelaxation.weightedTraceCost_smoothPhaseGraphChart_subset_eq
#print axioms
  CMVRelaxation.weightedTraceCost_finiteSmoothPhaseChartPiece_eq
#print axioms
  CMVRelaxation.weightedTraceCost_iUnion_eq_tsum
#print axioms
  CMVRelaxation.exists_smoothPhaseZeroTrace_cost_eq_tsum_graphPieces
