import CMVRegularGermInterfaceExtension

namespace CMVRelaxation.RegularTraceCornerComparison

namespace RegularCornerChartApplicability
#print axioms extensionEndpointRatio_lt_one

#print axioms frontier_window_subset_extensionCollar
#print axioms representative_inter_extensionCollar_eq_extensionLocalModel
#print axioms extensionLocalModel_frontier_inside_window
#print axioms extensionCompetitor_frontier
#print axioms extensionCompetitor_agrees_outside
#print axioms extensionCompetitor_complete_cost
#print axioms extensionCompetitor_weightedArea_defect_le

#print axioms ExtensionMetricApplicability.tendsto_negativeInterfaceArcLength_div
#print axioms ExtensionMetricApplicability.tendsto_extensionConnectorArcLength_div
#print axioms ExtensionMetricApplicability.tendsto_extensionMetricTraceGain_div
#print axioms
  SignedInterfaceApplicability.weightedTraceCost_negativeInterface_eq_hausdorff
#print axioms
  SignedIncidentPhaseApplicability.weightedTraceCost_extensionConnector_eq_phase_hausdorff
#print axioms ExtensionMetricApplicability.eventually_extension_local_inside_cost_lt
#print axioms
  ExtensionMetricApplicability.local_inside_cost_add_extensionMetricTraceGain
#print axioms
  ExtensionMetricApplicability.extensionCompetitor_complete_cost_add_gain_eq
#print axioms
  ExtensionMetricApplicability.eventually_extension_complete_cost_add_linear_le
#print axioms eventually_normalizedExtension_local_inside_cost_lt_of_conormal_lt
#print axioms
  eventually_normalizedExtension_complete_cost_add_linear_le_of_conormal_lt

#print axioms
  ExtensionMetricApplicability.extensionCompetitor_complete_cost_lt_of_local_inside_cost_lt
end RegularCornerChartApplicability
end CMVRelaxation.RegularTraceCornerComparison
