import CMVTransverseContactMomentum

open CMVTransverseContactVariation

#print axioms CMVTwoPatchGraphVariation.graphLengthIntegral_hasDerivAt
#print axioms
  CMVTransverseContactVariation.HorizontalGraphPatch.weightedGraphLength_hasDerivAt
#print axioms
  CMVTransverseContactVariation.HorizontalGraphPatch.weightedTraceCost_openGraphTrace_eq
#print axioms
  CMVTransverseContactVariation.HorizontalGraphPatch.weightedTraceCost_singleton
#print axioms
  CMVTransverseContactVariation.HorizontalGraphPatch.weightedTraceCost_closedGraphTrace_eq_open
#print axioms
  CMVTransverseContactVariation.ContactData.totalWeightedGraphLength_hasDerivAt
#print axioms
  CMVTransverseContactVariation.HorizontalGraphPatch.contactMomentum_hasDerivAt
#print axioms
  CMVTransverseContactVariation.ContactData.minus_firstVariation_eq_contact_sub_remainder
#print axioms
  CMVTransverseContactVariation.ContactData.plus_firstVariation_eq_neg_contact_sub_remainder
#print axioms
  CMVTransverseContactVariation.ContactData.compensationMomentumResponse_eq_neg_curvature_average
#print axioms
  CMVTransverseContactVariation.ContactData.abs_compensationMomentumResponse_le
#print axioms
  ContactData.contactFirstVariation_eq_transmissionDefect_sub_remainders
#print axioms
  CMVTransverseContactVariation.ContactData.abs_contactFirstVariation_sub_transmissionDefect_le
#print axioms
  ContactData.contactFirstVariation_ne_zero_of_error_lt_abs_transmissionDefect
#print axioms
  CMVTransverseContactVariation.ContactData.tendsto_contactFirstVariation_sub_transmissionDefect
#print axioms
  CMVTransverseContactVariation.ContactData.tendsto_contactFirstVariation
#print axioms
  ContactData.eventually_contactFirstVariation_ne_zero
#print axioms
  CMVTransverseContactVariation.ContactData.weightedTraceCosts_eq_graphLengths
#print axioms
  CMVTransverseContactVariation.ContactData.weightedTraceCost_commonContact_singleton
#print axioms
  ActualContactData.exists_exactArea_graphLength_descent_of_firstVariation_ne_zero
#print axioms
  ActualContactData.exists_exactArea_graphLength_descent_of_transmissionDefect
#print axioms
  CMVTransverseContactVariation.Examples.exact_area_graphLength_descent
#print axioms
  CMVTransverseContactVariation.LowerAboveExamples.transmissionDefect_ne_zero
#print axioms
  CMVTransverseContactVariation.LowerAboveExamples.exact_area_graphLength_descent
