import CMVTypeThreeLowerRecovery

#print axioms CMVRelaxation.TypeThreeRecovery.isSmoothDomain_semicircularOpenDisk
#print axioms CMVRelaxation.TypeThreeRecovery.carrier_eq_semicircularClosedDisk
#print axioms CMVRelaxation.TypeThreeRecovery.semicircularDiskConstantSequence_converges_carrier
#print axioms CMVRelaxation.TypeThreeRecovery.signedLowerLocalDomain_regular_at
#print axioms CMVRelaxation.TypeThreeRecovery.isOpen_lowerSurgeryDomain
#print axioms CMVRelaxation.TypeThreeRecovery.lowerSurgeryDomain_diff_windows
#print axioms CMVRelaxation.TypeThreeRecovery.characteristicDistance_lowerSurgeryDomain_carrier_le
#print axioms
  CMVRelaxation.TypeThreeRecovery.tendsto_characteristicDistance_lowerSurgeryDomain_carrier
#print axioms CMVRelaxation.TypeThreeRecovery.signedLowerContactTrace_regular_at
#print axioms CMVRelaxation.TypeThreeRecovery.exists_scaled_lowerReplacementTrace_hausdorffMeasure
#print axioms CMVRelaxation.TypeThreeRecovery.stripDensity_rightLowerContactTrace
#print axioms CMVRelaxation.TypeThreeRecovery.stripDensity_leftLowerContactTrace
#print axioms CMVRelaxation.TypeThreeRecovery.rightLowerContactTrace_mem_rightArcTrace
#print axioms CMVRelaxation.TypeThreeRecovery.leftLowerContactTrace_mem_leftArcTrace
