import CMVTwoPatchStationarity

#print axioms CMVTwoPatchGraphVariation.GraphPatch.weightedArea_variedCarrier
#print axioms CMVTwoPatchGraphVariation.GraphPatch.integrableOn_stripDensity_variedCarrier
#print axioms CMVTwoPatchGraphVariation.GraphPatch.variedCarrier_symmDiff_subset_graphTube
#print axioms CMVTwoPatchGraphVariation.GraphPatch.intervalIntegral_compensationBump
#print axioms CMVTwoPatchGraphVariation.weighted_velocity_integrals_cancel
#print axioms CMVTwoPatchGraphVariation.TwoPatchData.weightedArea_compensatedCarrier
#print axioms CMVTwoPatchGraphVariation.TwoPatchData.weightedArea_compensatedCarrier_interior
#print axioms CMVTwoPatchGraphVariation.TwoPatchData.weightedArea_compensatedCarrier_exterior
#print axioms CMVTwoPatchGraphVariation.weightedGraphLength_hasDerivAt
#print axioms CMVTwoPatchGraphVariation.totalWeightedGraphLength_hasDerivAt
#print axioms CMVTwoPatchGraphVariation.twoPatch_checkpoint
#print axioms CMVTwoPatchGraphVariation.twoPatch_checkpoint_with_firstVariation
#print axioms CMVTwoPatchGraphVariation.tsupport_velocityTwo_subset
#print axioms CMVTwoPatchGraphVariation.Examples.interiorApplication
#print axioms CMVTwoPatchGraphVariation.Examples.exteriorApplication
#print axioms
  CMVTwoPatchGraphVariation.PrimaryVariation.variedGraph_eq_of_not_mem_interval
#print axioms CMVTwoPatchGraphVariation.variedGraph_velocityTwo_eq_of_not_mem_interval
#print axioms CMVTwoPatchGraphVariation.TwoPatchData.closedGraphTubes_disjoint
#print axioms CMVTwoPatchGraphVariation.ActualTwoPatchData.weightedArea_variedCarrier
#print axioms
  CMVTwoPatchGraphVariation.ActualTwoPatchData.variedCarrier_symmDiff_subset_closedGraphTubes
#print axioms
  CMVTwoPatchGraphVariation.ActualTwoPatchData.mem_variedCarrier_iff_of_not_mem_closedGraphTubes
#print axioms CMVTwoPatchGraphVariation.actualTwoPatch_checkpoint_with_firstVariation
#print axioms CMVTwoPatchGraphVariation.GraphPatch.graphMomentum_hasDerivAt
#print axioms
  CMVTwoPatchGraphVariation.GraphPatch.integral_graphMomentum_mul_deriv_eq_neg_curvature_mul
#print axioms
  CMVTwoPatchGraphVariation.constrainedFirstVariation_eq_neg_weighted_residual
#print axioms
  CMVTwoPatchGraphVariation.totalWeightedGraphLength_hasDerivAt_constrainedFirstVariation
#print axioms
  CMVTwoPatchGraphVariation.ActualTwoPatchData.constrainedFirstVariation_eq_zero
#print axioms
  CMVTwoPatchGraphVariation.ActualTwoPatchData.orientedGraphCurvature_eq_anchor
#print axioms
  CMVTwoPatchGraphVariation.ActualTwoPatchData.exists_common_orientedGraphCurvature
#print axioms
  CMVTwoPatchGraphVariation.constrainedFirstVariation_normalizedPrimary_ne_zero_of_ne
#print axioms
  CMVTwoPatchGraphVariation.ActualTwoPatchData.exists_exactArea_graphLength_descent_of_ne
#print axioms
  CMVTwoPatchGraphVariation.FiniteActualGraphCollection.exists_common_orientedGraphCurvature
