import CMVTwoPatchCurvatureHypothesisContract

#print axioms
  CMVTwoPatchGraphVariation.ActualTwoPatchData.weightedArea_variedCarrier
#print axioms
  CMVTwoPatchGraphVariation.actualTwoPatch_checkpoint_with_firstVariation
#print axioms
  CMVTwoPatchGraphVariation.totalWeightedGraphLength_hasDerivAt_constrainedFirstVariation
#print axioms
  CMVTwoPatchGraphVariation.constrainedFirstVariation_eq_neg_weighted_residual
#print axioms
  CMVTwoPatchGraphVariation.ActualTwoPatchData.constrainedFirstVariation_eq_zero
#print axioms
  CMVTwoPatchGraphVariation.ActualTwoPatchData.stationarityResidual_eq_zero
#print axioms
  CMVTwoPatchGraphVariation.ActualTwoPatchData.orientedGraphCurvature_eq_anchor
#print axioms
  CMVTwoPatchGraphVariation.ActualTwoPatchData.exists_common_orientedGraphCurvature

#print axioms CMVTwoPatchGraphVariation.GraphPatch.euclideanSpeed_graphVelocity
#print axioms
  CMVTwoPatchGraphVariation.GraphPatch.arbitrarySpeedConstantCurvatureOn_graph
#print axioms CMVTwoPatchGraphVariation.GraphPatch.closed_graph_circle_identity
#print axioms
  CMVTwoPatchGraphVariation.GraphPatch.graph_eq_supportingLine_of_orientedGraphCurvature_eq_zero
#print axioms
  CMVTwoPatchGraphVariation.GraphPatch.euclideanSpeed_reparameterizedVelocity
#print axioms
  CMVTwoPatchGraphVariation.GraphPatch.signedEuclideanSpeed_reparameterizedVelocity
#print axioms
  CMVTwoPatchGraphVariation.GraphPatch.arbitrarySpeedConstantCurvatureOn_reparameterizedGraph
#print axioms
  CMVTwoPatchGraphVariation.GraphPatch.closed_reparameterizedGraph_circle_identity
#print axioms
  CMVTwoPatchGraphVariation.GraphPatch.closed_reparameterizedGraph_endpoints_circle_identity
#print axioms
  CMVTwoPatchGraphVariation.GraphPatch.reparamTrace_mem_supportingLine_of_curvature_zero
#print axioms
  CMVTwoPatchGraphVariation.ActualTwoPatchData.first_reparameterizedTrace_mem_frontier
#print axioms
  CMVTwoPatchGraphVariation.ActualTwoPatchData.second_reparameterizedTrace_mem_frontier
#print axioms
  CMVTwoPatchGraphVariation.ActualTwoPatchData.exists_common_supportingGeometry
#print axioms
  CMVTwoPatchGraphVariation.ActualTwoPatchData.exists_common_reparameterizedSupportingGeometry
#print axioms
  CMVTwoPatchGraphVariation.FiniteActualGraphCollection.member_reparameterizedTrace_mem_frontier
#print axioms
  CMVTwoPatchGraphVariation.FiniteActualGraphCollection.anchor_reparameterizedTrace_mem_frontier
#print axioms
  CMVTwoPatchGraphVariation.FiniteActualGraphCollection.exists_common_supportingGeometry
namespace CMVTwoPatchGraphVariation.FiniteActualGraphCollection
#print axioms exists_common_reparameterizedSupportingGeometry
end CMVTwoPatchGraphVariation.FiniteActualGraphCollection

#print axioms
  CMVTwoPatchGraphVariation.GraphPatch.Examples.below_identity_preserves_orientedCurvature
#print axioms
  CMVTwoPatchGraphVariation.GraphPatch.Examples.above_identity_reverses_orientedCurvature
#print axioms
  CMVTwoPatchGraphVariation.GraphPatch.Examples.above_reflection_preserves_orientedCurvature
#print axioms
  CMVTwoPatchGraphVariation.GraphPatch.Examples.below_reflection_reverses_orientedCurvature
#print axioms
  CMVTwoPatchGraphVariation.Examples.interior_affine_supportingLine
#print axioms
  CMVTwoPatchGraphVariation.Examples.exterior_affine_supportingLine
#print axioms CMVTwoPatchGraphVariation.CircularGraphExamples.application
#print axioms CMVTwoPatchGraphVariation.CircularGraphExamples.equalCurvature_pair
#print axioms
  CMVTwoPatchGraphVariation.HypothesisContract.actualArea_and_weightedLengthFirstVariation
#print axioms
  CMVTwoPatchGraphVariation.HypothesisContract.graphMinimality_to_reparameterizedGeometry
#print axioms
  CMVTwoPatchGraphVariation.HypothesisContract.relaxedMinimizer_to_commonCurvature_of_transfer
#check
  CMVTwoPatchGraphVariation.HypothesisContract.MissingRelaxedMinimizerToGraphStationarity
