import CMVWeightedCurveMultiplicity

open CMVRelaxation.WeightedCurveMultiplicity

#print axioms exists_countable_disjoint_injective_decomposition
#print axioms volume_image_criticalSource_eq_zero
#print axioms lintegral_branchCrossingWeight
#print axioms
  crossingMultiplicity_eq_weightedFiberMultiplicity_of_not_mem_criticalImage
#print axioms aemeasurable_weightedFiberMultiplicity
#print axioms lintegral_weightedFiberMultiplicity
#print axioms lintegral_curve_weightedFiberMultiplicity
#print axioms lintegral_curve_stripDensity_weightedFiberMultiplicity
#print axioms measurable_curveDirectionalMultiplicityCost
#print axioms measurable_curveStripDirectionalMultiplicityCost
#print axioms lintegral_curveDirectionalMultiplicityCost
#print axioms lintegral_curveStripDirectionalMultiplicityCost
#print axioms lintegral_graph_weightedFiberMultiplicity
#print axioms lintegral_graph_stripDensity_weightedFiberMultiplicity
#print axioms aemeasurable_graph_weightedFiberMultiplicity
#print axioms measurable_graphDirectionalMultiplicityCost
#print axioms setLIntegral_graphDirectionalMultiplicityCost
#print axioms measurable_graphStripDirectionalMultiplicityCost
#print axioms setLIntegral_graphStripDirectionalMultiplicityCost
#print axioms weightedFiberMultiplicity_sq_Icc
#print axioms weightedFiberMultiplicity_upperInterface_vertical_eq_top
#print axioms lintegral_upperInterface_segment_multiplicity
