/-
Copyright (c) 2026. Released under Apache 2.0 license.
-/
import MiddleFaceCell68
import MiddleFaceCell69
import MiddleFaceCell70
import MiddleFaceCell71
import MiddleFaceCell72
import MiddleFaceCell73
import MiddleFaceCell74
import MiddleFaceCell75
import MiddleFaceCell76
import MiddleFaceCell77
import MiddleFaceCell78
import MiddleFaceCell79

/-!
# Middle-face cells B0068 through B0079

Balanced branch-complete candidate exclusion over the closed union of exact
inventory bricks `B0068` through `B0079`.  Generated by
`middle_face_tiling/generate_lean_batch.py` from manifest payload hash
`d20c02a381696b4b1f3ea0790fcc089f0f026c4b9a2a23a50110287176334b4e`.
-/

noncomputable section

namespace MiddleFaceCells68To79

/-- Every modeled type-(iv) candidate in this closed batch fails
weighted-perimeter minimality. -/
theorem candidate_not_isWeightedPerimeterMinimizer
    {lam : ℝ}
    (hlower : (102681 / 100000 : ℝ) ≤ lam)
    (hupper : lam ≤ (102801 / 100000 : ℝ))
    (candidate : _root_.FourArcCandidate lam)
    (hcandidate : candidate.SatisfiesCMVTypeIVHypotheses) :
    ¬ candidate.IsWeightedPerimeterMinimizer := by
  by_cases hsplit74 : lam ≤ (102741 / 100000 : ℝ)
  · by_cases hsplit71 : lam ≤ (102711 / 100000 : ℝ)
    · by_cases hsplit69 : lam ≤ (102691 / 100000 : ℝ)
      · have hcell : MiddleFaceCell68.lamInterval.RealContains lam := by
          norm_num [MiddleFaceCell68.lamInterval, MiddleFaceCell68.brick,
            LeanSuffixReflective.QInterval.RealContains]
              at hlower hsplit69 ⊢
          exact ⟨hlower, hsplit69⟩
        exact
          MiddleFaceCell68.candidate_not_isWeightedPerimeterMinimizer
            hcell candidate hcandidate
      · have hlower69 : (102691 / 100000 : ℝ) ≤ lam :=
          (not_le.mp hsplit69).le
        by_cases hsplit70 : lam ≤ (102701 / 100000 : ℝ)
        · have hcell : MiddleFaceCell69.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell69.lamInterval, MiddleFaceCell69.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower69 hsplit70 ⊢
            exact ⟨hlower69, hsplit70⟩
          exact
            MiddleFaceCell69.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
        · have hlower70 : (102701 / 100000 : ℝ) ≤ lam :=
            (not_le.mp hsplit70).le
          have hcell : MiddleFaceCell70.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell70.lamInterval, MiddleFaceCell70.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower70 hsplit71 ⊢
            exact ⟨hlower70, hsplit71⟩
          exact
            MiddleFaceCell70.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
    · have hlower71 : (102711 / 100000 : ℝ) ≤ lam :=
        (not_le.mp hsplit71).le
      by_cases hsplit72 : lam ≤ (102721 / 100000 : ℝ)
      · have hcell : MiddleFaceCell71.lamInterval.RealContains lam := by
          norm_num [MiddleFaceCell71.lamInterval, MiddleFaceCell71.brick,
            LeanSuffixReflective.QInterval.RealContains]
              at hlower71 hsplit72 ⊢
          exact ⟨hlower71, hsplit72⟩
        exact
          MiddleFaceCell71.candidate_not_isWeightedPerimeterMinimizer
            hcell candidate hcandidate
      · have hlower72 : (102721 / 100000 : ℝ) ≤ lam :=
          (not_le.mp hsplit72).le
        by_cases hsplit73 : lam ≤ (102731 / 100000 : ℝ)
        · have hcell : MiddleFaceCell72.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell72.lamInterval, MiddleFaceCell72.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower72 hsplit73 ⊢
            exact ⟨hlower72, hsplit73⟩
          exact
            MiddleFaceCell72.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
        · have hlower73 : (102731 / 100000 : ℝ) ≤ lam :=
            (not_le.mp hsplit73).le
          have hcell : MiddleFaceCell73.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell73.lamInterval, MiddleFaceCell73.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower73 hsplit74 ⊢
            exact ⟨hlower73, hsplit74⟩
          exact
            MiddleFaceCell73.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
  · have hlower74 : (102741 / 100000 : ℝ) ≤ lam :=
      (not_le.mp hsplit74).le
    by_cases hsplit77 : lam ≤ (102771 / 100000 : ℝ)
    · by_cases hsplit75 : lam ≤ (102751 / 100000 : ℝ)
      · have hcell : MiddleFaceCell74.lamInterval.RealContains lam := by
          norm_num [MiddleFaceCell74.lamInterval, MiddleFaceCell74.brick,
            LeanSuffixReflective.QInterval.RealContains]
              at hlower74 hsplit75 ⊢
          exact ⟨hlower74, hsplit75⟩
        exact
          MiddleFaceCell74.candidate_not_isWeightedPerimeterMinimizer
            hcell candidate hcandidate
      · have hlower75 : (102751 / 100000 : ℝ) ≤ lam :=
          (not_le.mp hsplit75).le
        by_cases hsplit76 : lam ≤ (102761 / 100000 : ℝ)
        · have hcell : MiddleFaceCell75.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell75.lamInterval, MiddleFaceCell75.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower75 hsplit76 ⊢
            exact ⟨hlower75, hsplit76⟩
          exact
            MiddleFaceCell75.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
        · have hlower76 : (102761 / 100000 : ℝ) ≤ lam :=
            (not_le.mp hsplit76).le
          have hcell : MiddleFaceCell76.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell76.lamInterval, MiddleFaceCell76.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower76 hsplit77 ⊢
            exact ⟨hlower76, hsplit77⟩
          exact
            MiddleFaceCell76.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
    · have hlower77 : (102771 / 100000 : ℝ) ≤ lam :=
        (not_le.mp hsplit77).le
      by_cases hsplit78 : lam ≤ (102781 / 100000 : ℝ)
      · have hcell : MiddleFaceCell77.lamInterval.RealContains lam := by
          norm_num [MiddleFaceCell77.lamInterval, MiddleFaceCell77.brick,
            LeanSuffixReflective.QInterval.RealContains]
              at hlower77 hsplit78 ⊢
          exact ⟨hlower77, hsplit78⟩
        exact
          MiddleFaceCell77.candidate_not_isWeightedPerimeterMinimizer
            hcell candidate hcandidate
      · have hlower78 : (102781 / 100000 : ℝ) ≤ lam :=
          (not_le.mp hsplit78).le
        by_cases hsplit79 : lam ≤ (102791 / 100000 : ℝ)
        · have hcell : MiddleFaceCell78.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell78.lamInterval, MiddleFaceCell78.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower78 hsplit79 ⊢
            exact ⟨hlower78, hsplit79⟩
          exact
            MiddleFaceCell78.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
        · have hlower79 : (102791 / 100000 : ℝ) ≤ lam :=
            (not_le.mp hsplit79).le
          have hcell : MiddleFaceCell79.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell79.lamInterval, MiddleFaceCell79.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower79 hupper ⊢
            exact ⟨hlower79, hupper⟩
          exact
            MiddleFaceCell79.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate

end MiddleFaceCells68To79
