/-
Copyright (c) 2026. Released under Apache 2.0 license.
-/
import MiddleFaceCell80
import MiddleFaceCell81
import MiddleFaceCell82
import MiddleFaceCell83
import MiddleFaceCell84
import MiddleFaceCell85
import MiddleFaceCell86
import MiddleFaceCell87
import MiddleFaceCell88
import MiddleFaceCell89
import MiddleFaceCell90
import MiddleFaceCell91

/-!
# Middle-face cells B0080 through B0091

Balanced branch-complete candidate exclusion over the closed union of exact
inventory bricks `B0080` through `B0091`.  Generated by
`middle_face_tiling/generate_lean_batch.py` from manifest payload hash
`d20c02a381696b4b1f3ea0790fcc089f0f026c4b9a2a23a50110287176334b4e`.
-/

noncomputable section

namespace MiddleFaceCells80To91

/-- Every modeled type-(iv) candidate in this closed batch fails
weighted-perimeter minimality. -/
theorem candidate_not_isWeightedPerimeterMinimizer
    {lam : ℝ}
    (hlower : (102801 / 100000 : ℝ) ≤ lam)
    (hupper : lam ≤ (102921 / 100000 : ℝ))
    (candidate : _root_.FourArcCandidate lam)
    (hcandidate : candidate.SatisfiesCMVTypeIVHypotheses) :
    ¬ candidate.IsWeightedPerimeterMinimizer := by
  by_cases hsplit86 : lam ≤ (102861 / 100000 : ℝ)
  · by_cases hsplit83 : lam ≤ (102831 / 100000 : ℝ)
    · by_cases hsplit81 : lam ≤ (102811 / 100000 : ℝ)
      · have hcell : MiddleFaceCell80.lamInterval.RealContains lam := by
          norm_num [MiddleFaceCell80.lamInterval, MiddleFaceCell80.brick,
            LeanSuffixReflective.QInterval.RealContains]
              at hlower hsplit81 ⊢
          exact ⟨hlower, hsplit81⟩
        exact
          MiddleFaceCell80.candidate_not_isWeightedPerimeterMinimizer
            hcell candidate hcandidate
      · have hlower81 : (102811 / 100000 : ℝ) ≤ lam :=
          (not_le.mp hsplit81).le
        by_cases hsplit82 : lam ≤ (102821 / 100000 : ℝ)
        · have hcell : MiddleFaceCell81.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell81.lamInterval, MiddleFaceCell81.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower81 hsplit82 ⊢
            exact ⟨hlower81, hsplit82⟩
          exact
            MiddleFaceCell81.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
        · have hlower82 : (102821 / 100000 : ℝ) ≤ lam :=
            (not_le.mp hsplit82).le
          have hcell : MiddleFaceCell82.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell82.lamInterval, MiddleFaceCell82.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower82 hsplit83 ⊢
            exact ⟨hlower82, hsplit83⟩
          exact
            MiddleFaceCell82.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
    · have hlower83 : (102831 / 100000 : ℝ) ≤ lam :=
        (not_le.mp hsplit83).le
      by_cases hsplit84 : lam ≤ (102841 / 100000 : ℝ)
      · have hcell : MiddleFaceCell83.lamInterval.RealContains lam := by
          norm_num [MiddleFaceCell83.lamInterval, MiddleFaceCell83.brick,
            LeanSuffixReflective.QInterval.RealContains]
              at hlower83 hsplit84 ⊢
          exact ⟨hlower83, hsplit84⟩
        exact
          MiddleFaceCell83.candidate_not_isWeightedPerimeterMinimizer
            hcell candidate hcandidate
      · have hlower84 : (102841 / 100000 : ℝ) ≤ lam :=
          (not_le.mp hsplit84).le
        by_cases hsplit85 : lam ≤ (102851 / 100000 : ℝ)
        · have hcell : MiddleFaceCell84.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell84.lamInterval, MiddleFaceCell84.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower84 hsplit85 ⊢
            exact ⟨hlower84, hsplit85⟩
          exact
            MiddleFaceCell84.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
        · have hlower85 : (102851 / 100000 : ℝ) ≤ lam :=
            (not_le.mp hsplit85).le
          have hcell : MiddleFaceCell85.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell85.lamInterval, MiddleFaceCell85.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower85 hsplit86 ⊢
            exact ⟨hlower85, hsplit86⟩
          exact
            MiddleFaceCell85.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
  · have hlower86 : (102861 / 100000 : ℝ) ≤ lam :=
      (not_le.mp hsplit86).le
    by_cases hsplit89 : lam ≤ (102891 / 100000 : ℝ)
    · by_cases hsplit87 : lam ≤ (102871 / 100000 : ℝ)
      · have hcell : MiddleFaceCell86.lamInterval.RealContains lam := by
          norm_num [MiddleFaceCell86.lamInterval, MiddleFaceCell86.brick,
            LeanSuffixReflective.QInterval.RealContains]
              at hlower86 hsplit87 ⊢
          exact ⟨hlower86, hsplit87⟩
        exact
          MiddleFaceCell86.candidate_not_isWeightedPerimeterMinimizer
            hcell candidate hcandidate
      · have hlower87 : (102871 / 100000 : ℝ) ≤ lam :=
          (not_le.mp hsplit87).le
        by_cases hsplit88 : lam ≤ (102881 / 100000 : ℝ)
        · have hcell : MiddleFaceCell87.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell87.lamInterval, MiddleFaceCell87.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower87 hsplit88 ⊢
            exact ⟨hlower87, hsplit88⟩
          exact
            MiddleFaceCell87.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
        · have hlower88 : (102881 / 100000 : ℝ) ≤ lam :=
            (not_le.mp hsplit88).le
          have hcell : MiddleFaceCell88.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell88.lamInterval, MiddleFaceCell88.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower88 hsplit89 ⊢
            exact ⟨hlower88, hsplit89⟩
          exact
            MiddleFaceCell88.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
    · have hlower89 : (102891 / 100000 : ℝ) ≤ lam :=
        (not_le.mp hsplit89).le
      by_cases hsplit90 : lam ≤ (102901 / 100000 : ℝ)
      · have hcell : MiddleFaceCell89.lamInterval.RealContains lam := by
          norm_num [MiddleFaceCell89.lamInterval, MiddleFaceCell89.brick,
            LeanSuffixReflective.QInterval.RealContains]
              at hlower89 hsplit90 ⊢
          exact ⟨hlower89, hsplit90⟩
        exact
          MiddleFaceCell89.candidate_not_isWeightedPerimeterMinimizer
            hcell candidate hcandidate
      · have hlower90 : (102901 / 100000 : ℝ) ≤ lam :=
          (not_le.mp hsplit90).le
        by_cases hsplit91 : lam ≤ (102911 / 100000 : ℝ)
        · have hcell : MiddleFaceCell90.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell90.lamInterval, MiddleFaceCell90.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower90 hsplit91 ⊢
            exact ⟨hlower90, hsplit91⟩
          exact
            MiddleFaceCell90.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
        · have hlower91 : (102911 / 100000 : ℝ) ≤ lam :=
            (not_le.mp hsplit91).le
          have hcell : MiddleFaceCell91.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell91.lamInterval, MiddleFaceCell91.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower91 hupper ⊢
            exact ⟨hlower91, hupper⟩
          exact
            MiddleFaceCell91.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate

end MiddleFaceCells80To91
