/-
Copyright (c) 2026. Released under Apache 2.0 license.
-/
import MiddleFaceCell56
import MiddleFaceCell57
import MiddleFaceCell58
import MiddleFaceCell59
import MiddleFaceCell60
import MiddleFaceCell61
import MiddleFaceCell62
import MiddleFaceCell63
import MiddleFaceCell64
import MiddleFaceCell65
import MiddleFaceCell66
import MiddleFaceCell67

/-!
# Middle-face cells B0056 through B0067

Balanced branch-complete candidate exclusion over the closed union of exact
inventory bricks `B0056` through `B0067`.  Generated by
`middle_face_tiling/generate_lean_batch.py` from manifest payload hash
`d20c02a381696b4b1f3ea0790fcc089f0f026c4b9a2a23a50110287176334b4e`.
-/

noncomputable section

namespace MiddleFaceCells56To67

/-- Every modeled type-(iv) candidate in this closed batch fails
weighted-perimeter minimality. -/
theorem candidate_not_isWeightedPerimeterMinimizer
    {lam : ℝ}
    (hlower : (102561 / 100000 : ℝ) ≤ lam)
    (hupper : lam ≤ (102681 / 100000 : ℝ))
    (candidate : _root_.FourArcCandidate lam)
    (hcandidate : candidate.SatisfiesCMVTypeIVHypotheses) :
    ¬ candidate.IsWeightedPerimeterMinimizer := by
  by_cases hsplit62 : lam ≤ (102621 / 100000 : ℝ)
  · by_cases hsplit59 : lam ≤ (102591 / 100000 : ℝ)
    · by_cases hsplit57 : lam ≤ (102571 / 100000 : ℝ)
      · have hcell : MiddleFaceCell56.lamInterval.RealContains lam := by
          norm_num [MiddleFaceCell56.lamInterval, MiddleFaceCell56.brick,
            LeanSuffixReflective.QInterval.RealContains]
              at hlower hsplit57 ⊢
          exact ⟨hlower, hsplit57⟩
        exact
          MiddleFaceCell56.candidate_not_isWeightedPerimeterMinimizer
            hcell candidate hcandidate
      · have hlower57 : (102571 / 100000 : ℝ) ≤ lam :=
          (not_le.mp hsplit57).le
        by_cases hsplit58 : lam ≤ (102581 / 100000 : ℝ)
        · have hcell : MiddleFaceCell57.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell57.lamInterval, MiddleFaceCell57.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower57 hsplit58 ⊢
            exact ⟨hlower57, hsplit58⟩
          exact
            MiddleFaceCell57.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
        · have hlower58 : (102581 / 100000 : ℝ) ≤ lam :=
            (not_le.mp hsplit58).le
          have hcell : MiddleFaceCell58.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell58.lamInterval, MiddleFaceCell58.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower58 hsplit59 ⊢
            exact ⟨hlower58, hsplit59⟩
          exact
            MiddleFaceCell58.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
    · have hlower59 : (102591 / 100000 : ℝ) ≤ lam :=
        (not_le.mp hsplit59).le
      by_cases hsplit60 : lam ≤ (102601 / 100000 : ℝ)
      · have hcell : MiddleFaceCell59.lamInterval.RealContains lam := by
          norm_num [MiddleFaceCell59.lamInterval, MiddleFaceCell59.brick,
            LeanSuffixReflective.QInterval.RealContains]
              at hlower59 hsplit60 ⊢
          exact ⟨hlower59, hsplit60⟩
        exact
          MiddleFaceCell59.candidate_not_isWeightedPerimeterMinimizer
            hcell candidate hcandidate
      · have hlower60 : (102601 / 100000 : ℝ) ≤ lam :=
          (not_le.mp hsplit60).le
        by_cases hsplit61 : lam ≤ (102611 / 100000 : ℝ)
        · have hcell : MiddleFaceCell60.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell60.lamInterval, MiddleFaceCell60.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower60 hsplit61 ⊢
            exact ⟨hlower60, hsplit61⟩
          exact
            MiddleFaceCell60.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
        · have hlower61 : (102611 / 100000 : ℝ) ≤ lam :=
            (not_le.mp hsplit61).le
          have hcell : MiddleFaceCell61.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell61.lamInterval, MiddleFaceCell61.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower61 hsplit62 ⊢
            exact ⟨hlower61, hsplit62⟩
          exact
            MiddleFaceCell61.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
  · have hlower62 : (102621 / 100000 : ℝ) ≤ lam :=
      (not_le.mp hsplit62).le
    by_cases hsplit65 : lam ≤ (102651 / 100000 : ℝ)
    · by_cases hsplit63 : lam ≤ (102631 / 100000 : ℝ)
      · have hcell : MiddleFaceCell62.lamInterval.RealContains lam := by
          norm_num [MiddleFaceCell62.lamInterval, MiddleFaceCell62.brick,
            LeanSuffixReflective.QInterval.RealContains]
              at hlower62 hsplit63 ⊢
          exact ⟨hlower62, hsplit63⟩
        exact
          MiddleFaceCell62.candidate_not_isWeightedPerimeterMinimizer
            hcell candidate hcandidate
      · have hlower63 : (102631 / 100000 : ℝ) ≤ lam :=
          (not_le.mp hsplit63).le
        by_cases hsplit64 : lam ≤ (102641 / 100000 : ℝ)
        · have hcell : MiddleFaceCell63.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell63.lamInterval, MiddleFaceCell63.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower63 hsplit64 ⊢
            exact ⟨hlower63, hsplit64⟩
          exact
            MiddleFaceCell63.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
        · have hlower64 : (102641 / 100000 : ℝ) ≤ lam :=
            (not_le.mp hsplit64).le
          have hcell : MiddleFaceCell64.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell64.lamInterval, MiddleFaceCell64.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower64 hsplit65 ⊢
            exact ⟨hlower64, hsplit65⟩
          exact
            MiddleFaceCell64.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
    · have hlower65 : (102651 / 100000 : ℝ) ≤ lam :=
        (not_le.mp hsplit65).le
      by_cases hsplit66 : lam ≤ (102661 / 100000 : ℝ)
      · have hcell : MiddleFaceCell65.lamInterval.RealContains lam := by
          norm_num [MiddleFaceCell65.lamInterval, MiddleFaceCell65.brick,
            LeanSuffixReflective.QInterval.RealContains]
              at hlower65 hsplit66 ⊢
          exact ⟨hlower65, hsplit66⟩
        exact
          MiddleFaceCell65.candidate_not_isWeightedPerimeterMinimizer
            hcell candidate hcandidate
      · have hlower66 : (102661 / 100000 : ℝ) ≤ lam :=
          (not_le.mp hsplit66).le
        by_cases hsplit67 : lam ≤ (102671 / 100000 : ℝ)
        · have hcell : MiddleFaceCell66.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell66.lamInterval, MiddleFaceCell66.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower66 hsplit67 ⊢
            exact ⟨hlower66, hsplit67⟩
          exact
            MiddleFaceCell66.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
        · have hlower67 : (102671 / 100000 : ℝ) ≤ lam :=
            (not_le.mp hsplit67).le
          have hcell : MiddleFaceCell67.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell67.lamInterval, MiddleFaceCell67.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower67 hupper ⊢
            exact ⟨hlower67, hupper⟩
          exact
            MiddleFaceCell67.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate

end MiddleFaceCells56To67
