/-
Copyright (c) 2026. Released under Apache 2.0 license.
-/
import MiddleFaceCell44
import MiddleFaceCell45
import MiddleFaceCell46
import MiddleFaceCell47
import MiddleFaceCell48
import MiddleFaceCell49
import MiddleFaceCell50
import MiddleFaceCell51
import MiddleFaceCell52
import MiddleFaceCell53
import MiddleFaceCell54
import MiddleFaceCell55

/-!
# Middle-face cells B0044 through B0055

Balanced branch-complete candidate exclusion over the closed union of exact
inventory bricks `B0044` through `B0055`.  Generated by
`middle_face_tiling/generate_lean_batch.py` from manifest payload hash
`d20c02a381696b4b1f3ea0790fcc089f0f026c4b9a2a23a50110287176334b4e`.
-/

noncomputable section

namespace MiddleFaceCells44To55

/-- Every modeled type-(iv) candidate in this closed batch fails
weighted-perimeter minimality. -/
theorem candidate_not_isWeightedPerimeterMinimizer
    {lam : ℝ}
    (hlower : (102441 / 100000 : ℝ) ≤ lam)
    (hupper : lam ≤ (102561 / 100000 : ℝ))
    (candidate : _root_.FourArcCandidate lam)
    (hcandidate : candidate.SatisfiesCMVTypeIVHypotheses) :
    ¬ candidate.IsWeightedPerimeterMinimizer := by
  by_cases hsplit50 : lam ≤ (102501 / 100000 : ℝ)
  · by_cases hsplit47 : lam ≤ (102471 / 100000 : ℝ)
    · by_cases hsplit45 : lam ≤ (102451 / 100000 : ℝ)
      · have hcell : MiddleFaceCell44.lamInterval.RealContains lam := by
          norm_num [MiddleFaceCell44.lamInterval, MiddleFaceCell44.brick,
            LeanSuffixReflective.QInterval.RealContains]
              at hlower hsplit45 ⊢
          exact ⟨hlower, hsplit45⟩
        exact
          MiddleFaceCell44.candidate_not_isWeightedPerimeterMinimizer
            hcell candidate hcandidate
      · have hlower45 : (102451 / 100000 : ℝ) ≤ lam :=
          (not_le.mp hsplit45).le
        by_cases hsplit46 : lam ≤ (102461 / 100000 : ℝ)
        · have hcell : MiddleFaceCell45.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell45.lamInterval, MiddleFaceCell45.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower45 hsplit46 ⊢
            exact ⟨hlower45, hsplit46⟩
          exact
            MiddleFaceCell45.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
        · have hlower46 : (102461 / 100000 : ℝ) ≤ lam :=
            (not_le.mp hsplit46).le
          have hcell : MiddleFaceCell46.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell46.lamInterval, MiddleFaceCell46.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower46 hsplit47 ⊢
            exact ⟨hlower46, hsplit47⟩
          exact
            MiddleFaceCell46.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
    · have hlower47 : (102471 / 100000 : ℝ) ≤ lam :=
        (not_le.mp hsplit47).le
      by_cases hsplit48 : lam ≤ (102481 / 100000 : ℝ)
      · have hcell : MiddleFaceCell47.lamInterval.RealContains lam := by
          norm_num [MiddleFaceCell47.lamInterval, MiddleFaceCell47.brick,
            LeanSuffixReflective.QInterval.RealContains]
              at hlower47 hsplit48 ⊢
          exact ⟨hlower47, hsplit48⟩
        exact
          MiddleFaceCell47.candidate_not_isWeightedPerimeterMinimizer
            hcell candidate hcandidate
      · have hlower48 : (102481 / 100000 : ℝ) ≤ lam :=
          (not_le.mp hsplit48).le
        by_cases hsplit49 : lam ≤ (102491 / 100000 : ℝ)
        · have hcell : MiddleFaceCell48.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell48.lamInterval, MiddleFaceCell48.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower48 hsplit49 ⊢
            exact ⟨hlower48, hsplit49⟩
          exact
            MiddleFaceCell48.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
        · have hlower49 : (102491 / 100000 : ℝ) ≤ lam :=
            (not_le.mp hsplit49).le
          have hcell : MiddleFaceCell49.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell49.lamInterval, MiddleFaceCell49.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower49 hsplit50 ⊢
            exact ⟨hlower49, hsplit50⟩
          exact
            MiddleFaceCell49.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
  · have hlower50 : (102501 / 100000 : ℝ) ≤ lam :=
      (not_le.mp hsplit50).le
    by_cases hsplit53 : lam ≤ (102531 / 100000 : ℝ)
    · by_cases hsplit51 : lam ≤ (102511 / 100000 : ℝ)
      · have hcell : MiddleFaceCell50.lamInterval.RealContains lam := by
          norm_num [MiddleFaceCell50.lamInterval, MiddleFaceCell50.brick,
            LeanSuffixReflective.QInterval.RealContains]
              at hlower50 hsplit51 ⊢
          exact ⟨hlower50, hsplit51⟩
        exact
          MiddleFaceCell50.candidate_not_isWeightedPerimeterMinimizer
            hcell candidate hcandidate
      · have hlower51 : (102511 / 100000 : ℝ) ≤ lam :=
          (not_le.mp hsplit51).le
        by_cases hsplit52 : lam ≤ (102521 / 100000 : ℝ)
        · have hcell : MiddleFaceCell51.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell51.lamInterval, MiddleFaceCell51.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower51 hsplit52 ⊢
            exact ⟨hlower51, hsplit52⟩
          exact
            MiddleFaceCell51.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
        · have hlower52 : (102521 / 100000 : ℝ) ≤ lam :=
            (not_le.mp hsplit52).le
          have hcell : MiddleFaceCell52.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell52.lamInterval, MiddleFaceCell52.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower52 hsplit53 ⊢
            exact ⟨hlower52, hsplit53⟩
          exact
            MiddleFaceCell52.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
    · have hlower53 : (102531 / 100000 : ℝ) ≤ lam :=
        (not_le.mp hsplit53).le
      by_cases hsplit54 : lam ≤ (102541 / 100000 : ℝ)
      · have hcell : MiddleFaceCell53.lamInterval.RealContains lam := by
          norm_num [MiddleFaceCell53.lamInterval, MiddleFaceCell53.brick,
            LeanSuffixReflective.QInterval.RealContains]
              at hlower53 hsplit54 ⊢
          exact ⟨hlower53, hsplit54⟩
        exact
          MiddleFaceCell53.candidate_not_isWeightedPerimeterMinimizer
            hcell candidate hcandidate
      · have hlower54 : (102541 / 100000 : ℝ) ≤ lam :=
          (not_le.mp hsplit54).le
        by_cases hsplit55 : lam ≤ (102551 / 100000 : ℝ)
        · have hcell : MiddleFaceCell54.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell54.lamInterval, MiddleFaceCell54.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower54 hsplit55 ⊢
            exact ⟨hlower54, hsplit55⟩
          exact
            MiddleFaceCell54.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
        · have hlower55 : (102551 / 100000 : ℝ) ≤ lam :=
            (not_le.mp hsplit55).le
          have hcell : MiddleFaceCell55.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell55.lamInterval, MiddleFaceCell55.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower55 hupper ⊢
            exact ⟨hlower55, hupper⟩
          exact
            MiddleFaceCell55.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate

end MiddleFaceCells44To55
