/-
Copyright (c) 2026. Released under Apache 2.0 license.
-/
import MiddleFaceCell20
import MiddleFaceCell21
import MiddleFaceCell22
import MiddleFaceCell23
import MiddleFaceCell24
import MiddleFaceCell25
import MiddleFaceCell26
import MiddleFaceCell27
import MiddleFaceCell28
import MiddleFaceCell29
import MiddleFaceCell30
import MiddleFaceCell31

/-!
# Middle-face cells B0020 through B0031

Balanced branch-complete candidate exclusion over the closed union of exact
inventory bricks `B0020` through `B0031`.  Generated by
`middle_face_tiling/generate_lean_batch.py` from manifest payload hash
`d20c02a381696b4b1f3ea0790fcc089f0f026c4b9a2a23a50110287176334b4e`.
-/

noncomputable section

namespace MiddleFaceCells20To31

/-- Every modeled type-(iv) candidate in this closed batch fails
weighted-perimeter minimality. -/
theorem candidate_not_isWeightedPerimeterMinimizer
    {lam : ℝ}
    (hlower : (102201 / 100000 : ℝ) ≤ lam)
    (hupper : lam ≤ (102321 / 100000 : ℝ))
    (candidate : _root_.FourArcCandidate lam)
    (hcandidate : candidate.SatisfiesCMVTypeIVHypotheses) :
    ¬ candidate.IsWeightedPerimeterMinimizer := by
  by_cases hsplit26 : lam ≤ (102261 / 100000 : ℝ)
  · by_cases hsplit23 : lam ≤ (102231 / 100000 : ℝ)
    · by_cases hsplit21 : lam ≤ (102211 / 100000 : ℝ)
      · have hcell : MiddleFaceCell20.lamInterval.RealContains lam := by
          norm_num [MiddleFaceCell20.lamInterval, MiddleFaceCell20.brick,
            LeanSuffixReflective.QInterval.RealContains]
              at hlower hsplit21 ⊢
          exact ⟨hlower, hsplit21⟩
        exact
          MiddleFaceCell20.candidate_not_isWeightedPerimeterMinimizer
            hcell candidate hcandidate
      · have hlower21 : (102211 / 100000 : ℝ) ≤ lam :=
          (not_le.mp hsplit21).le
        by_cases hsplit22 : lam ≤ (102221 / 100000 : ℝ)
        · have hcell : MiddleFaceCell21.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell21.lamInterval, MiddleFaceCell21.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower21 hsplit22 ⊢
            exact ⟨hlower21, hsplit22⟩
          exact
            MiddleFaceCell21.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
        · have hlower22 : (102221 / 100000 : ℝ) ≤ lam :=
            (not_le.mp hsplit22).le
          have hcell : MiddleFaceCell22.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell22.lamInterval, MiddleFaceCell22.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower22 hsplit23 ⊢
            exact ⟨hlower22, hsplit23⟩
          exact
            MiddleFaceCell22.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
    · have hlower23 : (102231 / 100000 : ℝ) ≤ lam :=
        (not_le.mp hsplit23).le
      by_cases hsplit24 : lam ≤ (102241 / 100000 : ℝ)
      · have hcell : MiddleFaceCell23.lamInterval.RealContains lam := by
          norm_num [MiddleFaceCell23.lamInterval, MiddleFaceCell23.brick,
            LeanSuffixReflective.QInterval.RealContains]
              at hlower23 hsplit24 ⊢
          exact ⟨hlower23, hsplit24⟩
        exact
          MiddleFaceCell23.candidate_not_isWeightedPerimeterMinimizer
            hcell candidate hcandidate
      · have hlower24 : (102241 / 100000 : ℝ) ≤ lam :=
          (not_le.mp hsplit24).le
        by_cases hsplit25 : lam ≤ (102251 / 100000 : ℝ)
        · have hcell : MiddleFaceCell24.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell24.lamInterval, MiddleFaceCell24.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower24 hsplit25 ⊢
            exact ⟨hlower24, hsplit25⟩
          exact
            MiddleFaceCell24.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
        · have hlower25 : (102251 / 100000 : ℝ) ≤ lam :=
            (not_le.mp hsplit25).le
          have hcell : MiddleFaceCell25.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell25.lamInterval, MiddleFaceCell25.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower25 hsplit26 ⊢
            exact ⟨hlower25, hsplit26⟩
          exact
            MiddleFaceCell25.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
  · have hlower26 : (102261 / 100000 : ℝ) ≤ lam :=
      (not_le.mp hsplit26).le
    by_cases hsplit29 : lam ≤ (102291 / 100000 : ℝ)
    · by_cases hsplit27 : lam ≤ (102271 / 100000 : ℝ)
      · have hcell : MiddleFaceCell26.lamInterval.RealContains lam := by
          norm_num [MiddleFaceCell26.lamInterval, MiddleFaceCell26.brick,
            LeanSuffixReflective.QInterval.RealContains]
              at hlower26 hsplit27 ⊢
          exact ⟨hlower26, hsplit27⟩
        exact
          MiddleFaceCell26.candidate_not_isWeightedPerimeterMinimizer
            hcell candidate hcandidate
      · have hlower27 : (102271 / 100000 : ℝ) ≤ lam :=
          (not_le.mp hsplit27).le
        by_cases hsplit28 : lam ≤ (102281 / 100000 : ℝ)
        · have hcell : MiddleFaceCell27.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell27.lamInterval, MiddleFaceCell27.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower27 hsplit28 ⊢
            exact ⟨hlower27, hsplit28⟩
          exact
            MiddleFaceCell27.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
        · have hlower28 : (102281 / 100000 : ℝ) ≤ lam :=
            (not_le.mp hsplit28).le
          have hcell : MiddleFaceCell28.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell28.lamInterval, MiddleFaceCell28.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower28 hsplit29 ⊢
            exact ⟨hlower28, hsplit29⟩
          exact
            MiddleFaceCell28.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
    · have hlower29 : (102291 / 100000 : ℝ) ≤ lam :=
        (not_le.mp hsplit29).le
      by_cases hsplit30 : lam ≤ (102301 / 100000 : ℝ)
      · have hcell : MiddleFaceCell29.lamInterval.RealContains lam := by
          norm_num [MiddleFaceCell29.lamInterval, MiddleFaceCell29.brick,
            LeanSuffixReflective.QInterval.RealContains]
              at hlower29 hsplit30 ⊢
          exact ⟨hlower29, hsplit30⟩
        exact
          MiddleFaceCell29.candidate_not_isWeightedPerimeterMinimizer
            hcell candidate hcandidate
      · have hlower30 : (102301 / 100000 : ℝ) ≤ lam :=
          (not_le.mp hsplit30).le
        by_cases hsplit31 : lam ≤ (102311 / 100000 : ℝ)
        · have hcell : MiddleFaceCell30.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell30.lamInterval, MiddleFaceCell30.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower30 hsplit31 ⊢
            exact ⟨hlower30, hsplit31⟩
          exact
            MiddleFaceCell30.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
        · have hlower31 : (102311 / 100000 : ℝ) ≤ lam :=
            (not_le.mp hsplit31).le
          have hcell : MiddleFaceCell31.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell31.lamInterval, MiddleFaceCell31.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower31 hupper ⊢
            exact ⟨hlower31, hupper⟩
          exact
            MiddleFaceCell31.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate

end MiddleFaceCells20To31
