/-
Copyright (c) 2026. Released under Apache 2.0 license.
-/
import MiddleFaceCell32
import MiddleFaceCell33
import MiddleFaceCell34
import MiddleFaceCell35
import MiddleFaceCell36
import MiddleFaceCell37
import MiddleFaceCell38
import MiddleFaceCell39
import MiddleFaceCell40
import MiddleFaceCell41
import MiddleFaceCell42
import MiddleFaceCell43

/-!
# Middle-face cells B0032 through B0043

Balanced branch-complete candidate exclusion over the closed union of exact
inventory bricks `B0032` through `B0043`.  Generated by
`middle_face_tiling/generate_lean_batch.py` from manifest payload hash
`d20c02a381696b4b1f3ea0790fcc089f0f026c4b9a2a23a50110287176334b4e`.
-/

noncomputable section

namespace MiddleFaceCells32To43

/-- Every modeled type-(iv) candidate in this closed batch fails
weighted-perimeter minimality. -/
theorem candidate_not_isWeightedPerimeterMinimizer
    {lam : ℝ}
    (hlower : (102321 / 100000 : ℝ) ≤ lam)
    (hupper : lam ≤ (102441 / 100000 : ℝ))
    (candidate : _root_.FourArcCandidate lam)
    (hcandidate : candidate.SatisfiesCMVTypeIVHypotheses) :
    ¬ candidate.IsWeightedPerimeterMinimizer := by
  by_cases hsplit38 : lam ≤ (102381 / 100000 : ℝ)
  · by_cases hsplit35 : lam ≤ (102351 / 100000 : ℝ)
    · by_cases hsplit33 : lam ≤ (102331 / 100000 : ℝ)
      · have hcell : MiddleFaceCell32.lamInterval.RealContains lam := by
          norm_num [MiddleFaceCell32.lamInterval, MiddleFaceCell32.brick,
            LeanSuffixReflective.QInterval.RealContains]
              at hlower hsplit33 ⊢
          exact ⟨hlower, hsplit33⟩
        exact
          MiddleFaceCell32.candidate_not_isWeightedPerimeterMinimizer
            hcell candidate hcandidate
      · have hlower33 : (102331 / 100000 : ℝ) ≤ lam :=
          (not_le.mp hsplit33).le
        by_cases hsplit34 : lam ≤ (102341 / 100000 : ℝ)
        · have hcell : MiddleFaceCell33.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell33.lamInterval, MiddleFaceCell33.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower33 hsplit34 ⊢
            exact ⟨hlower33, hsplit34⟩
          exact
            MiddleFaceCell33.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
        · have hlower34 : (102341 / 100000 : ℝ) ≤ lam :=
            (not_le.mp hsplit34).le
          have hcell : MiddleFaceCell34.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell34.lamInterval, MiddleFaceCell34.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower34 hsplit35 ⊢
            exact ⟨hlower34, hsplit35⟩
          exact
            MiddleFaceCell34.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
    · have hlower35 : (102351 / 100000 : ℝ) ≤ lam :=
        (not_le.mp hsplit35).le
      by_cases hsplit36 : lam ≤ (102361 / 100000 : ℝ)
      · have hcell : MiddleFaceCell35.lamInterval.RealContains lam := by
          norm_num [MiddleFaceCell35.lamInterval, MiddleFaceCell35.brick,
            LeanSuffixReflective.QInterval.RealContains]
              at hlower35 hsplit36 ⊢
          exact ⟨hlower35, hsplit36⟩
        exact
          MiddleFaceCell35.candidate_not_isWeightedPerimeterMinimizer
            hcell candidate hcandidate
      · have hlower36 : (102361 / 100000 : ℝ) ≤ lam :=
          (not_le.mp hsplit36).le
        by_cases hsplit37 : lam ≤ (102371 / 100000 : ℝ)
        · have hcell : MiddleFaceCell36.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell36.lamInterval, MiddleFaceCell36.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower36 hsplit37 ⊢
            exact ⟨hlower36, hsplit37⟩
          exact
            MiddleFaceCell36.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
        · have hlower37 : (102371 / 100000 : ℝ) ≤ lam :=
            (not_le.mp hsplit37).le
          have hcell : MiddleFaceCell37.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell37.lamInterval, MiddleFaceCell37.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower37 hsplit38 ⊢
            exact ⟨hlower37, hsplit38⟩
          exact
            MiddleFaceCell37.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
  · have hlower38 : (102381 / 100000 : ℝ) ≤ lam :=
      (not_le.mp hsplit38).le
    by_cases hsplit41 : lam ≤ (102411 / 100000 : ℝ)
    · by_cases hsplit39 : lam ≤ (102391 / 100000 : ℝ)
      · have hcell : MiddleFaceCell38.lamInterval.RealContains lam := by
          norm_num [MiddleFaceCell38.lamInterval, MiddleFaceCell38.brick,
            LeanSuffixReflective.QInterval.RealContains]
              at hlower38 hsplit39 ⊢
          exact ⟨hlower38, hsplit39⟩
        exact
          MiddleFaceCell38.candidate_not_isWeightedPerimeterMinimizer
            hcell candidate hcandidate
      · have hlower39 : (102391 / 100000 : ℝ) ≤ lam :=
          (not_le.mp hsplit39).le
        by_cases hsplit40 : lam ≤ (102401 / 100000 : ℝ)
        · have hcell : MiddleFaceCell39.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell39.lamInterval, MiddleFaceCell39.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower39 hsplit40 ⊢
            exact ⟨hlower39, hsplit40⟩
          exact
            MiddleFaceCell39.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
        · have hlower40 : (102401 / 100000 : ℝ) ≤ lam :=
            (not_le.mp hsplit40).le
          have hcell : MiddleFaceCell40.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell40.lamInterval, MiddleFaceCell40.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower40 hsplit41 ⊢
            exact ⟨hlower40, hsplit41⟩
          exact
            MiddleFaceCell40.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
    · have hlower41 : (102411 / 100000 : ℝ) ≤ lam :=
        (not_le.mp hsplit41).le
      by_cases hsplit42 : lam ≤ (102421 / 100000 : ℝ)
      · have hcell : MiddleFaceCell41.lamInterval.RealContains lam := by
          norm_num [MiddleFaceCell41.lamInterval, MiddleFaceCell41.brick,
            LeanSuffixReflective.QInterval.RealContains]
              at hlower41 hsplit42 ⊢
          exact ⟨hlower41, hsplit42⟩
        exact
          MiddleFaceCell41.candidate_not_isWeightedPerimeterMinimizer
            hcell candidate hcandidate
      · have hlower42 : (102421 / 100000 : ℝ) ≤ lam :=
          (not_le.mp hsplit42).le
        by_cases hsplit43 : lam ≤ (102431 / 100000 : ℝ)
        · have hcell : MiddleFaceCell42.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell42.lamInterval, MiddleFaceCell42.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower42 hsplit43 ⊢
            exact ⟨hlower42, hsplit43⟩
          exact
            MiddleFaceCell42.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
        · have hlower43 : (102431 / 100000 : ℝ) ≤ lam :=
            (not_le.mp hsplit43).le
          have hcell : MiddleFaceCell43.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell43.lamInterval, MiddleFaceCell43.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower43 hupper ⊢
            exact ⟨hlower43, hupper⟩
          exact
            MiddleFaceCell43.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate

end MiddleFaceCells32To43
