/-
Copyright (c) 2026. Released under Apache 2.0 license.
-/
import MiddleFaceCell0
import MiddleFaceCell1
import MiddleFaceCell2
import MiddleFaceCell3
import MiddleFaceCell4
import MiddleFaceCell5
import MiddleFaceCell6
import MiddleFaceCell7
import MiddleFaceCell8
import MiddleFaceCell9
import MiddleFaceCell10
import MiddleFaceCell11
import MiddleFaceCell12
import MiddleFaceCell13
import MiddleFaceCell14
import MiddleFaceCell15
import MiddleFaceCell16
import MiddleFaceCell17
import MiddleFaceCell18
import MiddleFaceCell19

/-!
# Middle-face cells B0000 through B0019

Balanced branch-complete candidate exclusion over the closed union of exact
inventory bricks `B0000` through `B0019`.  Generated by
`middle_face_tiling/generate_lean_batch.py` from manifest payload hash
`d20c02a381696b4b1f3ea0790fcc089f0f026c4b9a2a23a50110287176334b4e`.
-/

noncomputable section

namespace MiddleFaceCells0To19

/-- Every modeled type-(iv) candidate in this closed batch fails
weighted-perimeter minimality. -/
theorem candidate_not_isWeightedPerimeterMinimizer
    {lam : ℝ}
    (hlower : (102001 / 100000 : ℝ) ≤ lam)
    (hupper : lam ≤ (102201 / 100000 : ℝ))
    (candidate : _root_.FourArcCandidate lam)
    (hcandidate : candidate.SatisfiesCMVTypeIVHypotheses) :
    ¬ candidate.IsWeightedPerimeterMinimizer := by
  by_cases hsplit10 : lam ≤ (102101 / 100000 : ℝ)
  · by_cases hsplit5 : lam ≤ (102051 / 100000 : ℝ)
    · by_cases hsplit2 : lam ≤ (102021 / 100000 : ℝ)
      · by_cases hsplit1 : lam ≤ (102011 / 100000 : ℝ)
        · have hcell : MiddleFaceCell0.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell0.lamInterval, MiddleFaceCell0.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower hsplit1 ⊢
            exact ⟨hlower, hsplit1⟩
          exact
            MiddleFaceCell0.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
        · have hlower1 : (102011 / 100000 : ℝ) ≤ lam :=
            (not_le.mp hsplit1).le
          have hcell : MiddleFaceCell1.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell1.lamInterval, MiddleFaceCell1.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower1 hsplit2 ⊢
            exact ⟨hlower1, hsplit2⟩
          exact
            MiddleFaceCell1.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
      · have hlower2 : (102021 / 100000 : ℝ) ≤ lam :=
          (not_le.mp hsplit2).le
        by_cases hsplit3 : lam ≤ (102031 / 100000 : ℝ)
        · have hcell : MiddleFaceCell2.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell2.lamInterval, MiddleFaceCell2.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower2 hsplit3 ⊢
            exact ⟨hlower2, hsplit3⟩
          exact
            MiddleFaceCell2.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
        · have hlower3 : (102031 / 100000 : ℝ) ≤ lam :=
            (not_le.mp hsplit3).le
          by_cases hsplit4 : lam ≤ (102041 / 100000 : ℝ)
          · have hcell : MiddleFaceCell3.lamInterval.RealContains lam := by
              norm_num [MiddleFaceCell3.lamInterval, MiddleFaceCell3.brick,
                LeanSuffixReflective.QInterval.RealContains]
                  at hlower3 hsplit4 ⊢
              exact ⟨hlower3, hsplit4⟩
            exact
              MiddleFaceCell3.candidate_not_isWeightedPerimeterMinimizer
                hcell candidate hcandidate
          · have hlower4 : (102041 / 100000 : ℝ) ≤ lam :=
              (not_le.mp hsplit4).le
            have hcell : MiddleFaceCell4.lamInterval.RealContains lam := by
              norm_num [MiddleFaceCell4.lamInterval, MiddleFaceCell4.brick,
                LeanSuffixReflective.QInterval.RealContains]
                  at hlower4 hsplit5 ⊢
              exact ⟨hlower4, hsplit5⟩
            exact
              MiddleFaceCell4.candidate_not_isWeightedPerimeterMinimizer
                hcell candidate hcandidate
    · have hlower5 : (102051 / 100000 : ℝ) ≤ lam :=
        (not_le.mp hsplit5).le
      by_cases hsplit7 : lam ≤ (102071 / 100000 : ℝ)
      · by_cases hsplit6 : lam ≤ (102061 / 100000 : ℝ)
        · have hcell : MiddleFaceCell5.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell5.lamInterval, MiddleFaceCell5.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower5 hsplit6 ⊢
            exact ⟨hlower5, hsplit6⟩
          exact
            MiddleFaceCell5.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
        · have hlower6 : (102061 / 100000 : ℝ) ≤ lam :=
            (not_le.mp hsplit6).le
          have hcell : MiddleFaceCell6.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell6.lamInterval, MiddleFaceCell6.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower6 hsplit7 ⊢
            exact ⟨hlower6, hsplit7⟩
          exact
            MiddleFaceCell6.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
      · have hlower7 : (102071 / 100000 : ℝ) ≤ lam :=
          (not_le.mp hsplit7).le
        by_cases hsplit8 : lam ≤ (102081 / 100000 : ℝ)
        · have hcell : MiddleFaceCell7.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell7.lamInterval, MiddleFaceCell7.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower7 hsplit8 ⊢
            exact ⟨hlower7, hsplit8⟩
          exact
            MiddleFaceCell7.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
        · have hlower8 : (102081 / 100000 : ℝ) ≤ lam :=
            (not_le.mp hsplit8).le
          by_cases hsplit9 : lam ≤ (102091 / 100000 : ℝ)
          · have hcell : MiddleFaceCell8.lamInterval.RealContains lam := by
              norm_num [MiddleFaceCell8.lamInterval, MiddleFaceCell8.brick,
                LeanSuffixReflective.QInterval.RealContains]
                  at hlower8 hsplit9 ⊢
              exact ⟨hlower8, hsplit9⟩
            exact
              MiddleFaceCell8.candidate_not_isWeightedPerimeterMinimizer
                hcell candidate hcandidate
          · have hlower9 : (102091 / 100000 : ℝ) ≤ lam :=
              (not_le.mp hsplit9).le
            have hcell : MiddleFaceCell9.lamInterval.RealContains lam := by
              norm_num [MiddleFaceCell9.lamInterval, MiddleFaceCell9.brick,
                LeanSuffixReflective.QInterval.RealContains]
                  at hlower9 hsplit10 ⊢
              exact ⟨hlower9, hsplit10⟩
            exact
              MiddleFaceCell9.candidate_not_isWeightedPerimeterMinimizer
                hcell candidate hcandidate
  · have hlower10 : (102101 / 100000 : ℝ) ≤ lam :=
      (not_le.mp hsplit10).le
    by_cases hsplit15 : lam ≤ (102151 / 100000 : ℝ)
    · by_cases hsplit12 : lam ≤ (102121 / 100000 : ℝ)
      · by_cases hsplit11 : lam ≤ (102111 / 100000 : ℝ)
        · have hcell : MiddleFaceCell10.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell10.lamInterval, MiddleFaceCell10.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower10 hsplit11 ⊢
            exact ⟨hlower10, hsplit11⟩
          exact
            MiddleFaceCell10.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
        · have hlower11 : (102111 / 100000 : ℝ) ≤ lam :=
            (not_le.mp hsplit11).le
          have hcell : MiddleFaceCell11.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell11.lamInterval, MiddleFaceCell11.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower11 hsplit12 ⊢
            exact ⟨hlower11, hsplit12⟩
          exact
            MiddleFaceCell11.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
      · have hlower12 : (102121 / 100000 : ℝ) ≤ lam :=
          (not_le.mp hsplit12).le
        by_cases hsplit13 : lam ≤ (102131 / 100000 : ℝ)
        · have hcell : MiddleFaceCell12.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell12.lamInterval, MiddleFaceCell12.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower12 hsplit13 ⊢
            exact ⟨hlower12, hsplit13⟩
          exact
            MiddleFaceCell12.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
        · have hlower13 : (102131 / 100000 : ℝ) ≤ lam :=
            (not_le.mp hsplit13).le
          by_cases hsplit14 : lam ≤ (102141 / 100000 : ℝ)
          · have hcell : MiddleFaceCell13.lamInterval.RealContains lam := by
              norm_num [MiddleFaceCell13.lamInterval, MiddleFaceCell13.brick,
                LeanSuffixReflective.QInterval.RealContains]
                  at hlower13 hsplit14 ⊢
              exact ⟨hlower13, hsplit14⟩
            exact
              MiddleFaceCell13.candidate_not_isWeightedPerimeterMinimizer
                hcell candidate hcandidate
          · have hlower14 : (102141 / 100000 : ℝ) ≤ lam :=
              (not_le.mp hsplit14).le
            have hcell : MiddleFaceCell14.lamInterval.RealContains lam := by
              norm_num [MiddleFaceCell14.lamInterval, MiddleFaceCell14.brick,
                LeanSuffixReflective.QInterval.RealContains]
                  at hlower14 hsplit15 ⊢
              exact ⟨hlower14, hsplit15⟩
            exact
              MiddleFaceCell14.candidate_not_isWeightedPerimeterMinimizer
                hcell candidate hcandidate
    · have hlower15 : (102151 / 100000 : ℝ) ≤ lam :=
        (not_le.mp hsplit15).le
      by_cases hsplit17 : lam ≤ (102171 / 100000 : ℝ)
      · by_cases hsplit16 : lam ≤ (102161 / 100000 : ℝ)
        · have hcell : MiddleFaceCell15.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell15.lamInterval, MiddleFaceCell15.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower15 hsplit16 ⊢
            exact ⟨hlower15, hsplit16⟩
          exact
            MiddleFaceCell15.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
        · have hlower16 : (102161 / 100000 : ℝ) ≤ lam :=
            (not_le.mp hsplit16).le
          have hcell : MiddleFaceCell16.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell16.lamInterval, MiddleFaceCell16.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower16 hsplit17 ⊢
            exact ⟨hlower16, hsplit17⟩
          exact
            MiddleFaceCell16.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
      · have hlower17 : (102171 / 100000 : ℝ) ≤ lam :=
          (not_le.mp hsplit17).le
        by_cases hsplit18 : lam ≤ (102181 / 100000 : ℝ)
        · have hcell : MiddleFaceCell17.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell17.lamInterval, MiddleFaceCell17.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower17 hsplit18 ⊢
            exact ⟨hlower17, hsplit18⟩
          exact
            MiddleFaceCell17.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
        · have hlower18 : (102181 / 100000 : ℝ) ≤ lam :=
            (not_le.mp hsplit18).le
          by_cases hsplit19 : lam ≤ (102191 / 100000 : ℝ)
          · have hcell : MiddleFaceCell18.lamInterval.RealContains lam := by
              norm_num [MiddleFaceCell18.lamInterval, MiddleFaceCell18.brick,
                LeanSuffixReflective.QInterval.RealContains]
                  at hlower18 hsplit19 ⊢
              exact ⟨hlower18, hsplit19⟩
            exact
              MiddleFaceCell18.candidate_not_isWeightedPerimeterMinimizer
                hcell candidate hcandidate
          · have hlower19 : (102191 / 100000 : ℝ) ≤ lam :=
              (not_le.mp hsplit19).le
            have hcell : MiddleFaceCell19.lamInterval.RealContains lam := by
              norm_num [MiddleFaceCell19.lamInterval, MiddleFaceCell19.brick,
                LeanSuffixReflective.QInterval.RealContains]
                  at hlower19 hupper ⊢
              exact ⟨hlower19, hupper⟩
            exact
              MiddleFaceCell19.candidate_not_isWeightedPerimeterMinimizer
                hcell candidate hcandidate

end MiddleFaceCells0To19
