/-
Copyright (c) 2026. Released under Apache 2.0 license.
-/
import MiddleFaceCell92
import MiddleFaceCell93
import MiddleFaceCell94
import MiddleFaceCell95
import MiddleFaceCell96
import MiddleFaceCell97
import MiddleFaceCell98
import MiddleFaceCell99
import MiddleFaceCell100
import MiddleFaceCell101
import MiddleFaceCell102
import MiddleFaceCell103

/-!
# Middle-face cells B0092 through B0103

Balanced branch-complete candidate exclusion over the closed union of exact
inventory bricks `B0092` through `B0103`.  Generated by
`middle_face_tiling/generate_lean_batch.py` from manifest payload hash
`d20c02a381696b4b1f3ea0790fcc089f0f026c4b9a2a23a50110287176334b4e`.
-/

noncomputable section

namespace MiddleFaceCells92To103

/-- Every modeled type-(iv) candidate in this closed batch fails
weighted-perimeter minimality. -/
theorem candidate_not_isWeightedPerimeterMinimizer
    {lam : ℝ}
    (hlower : (102921 / 100000 : ℝ) ≤ lam)
    (hupper : lam ≤ (103041 / 100000 : ℝ))
    (candidate : _root_.FourArcCandidate lam)
    (hcandidate : candidate.SatisfiesCMVTypeIVHypotheses) :
    ¬ candidate.IsWeightedPerimeterMinimizer := by
  by_cases hsplit98 : lam ≤ (102981 / 100000 : ℝ)
  · by_cases hsplit95 : lam ≤ (102951 / 100000 : ℝ)
    · by_cases hsplit93 : lam ≤ (102931 / 100000 : ℝ)
      · have hcell : MiddleFaceCell92.lamInterval.RealContains lam := by
          norm_num [MiddleFaceCell92.lamInterval, MiddleFaceCell92.brick,
            LeanSuffixReflective.QInterval.RealContains]
              at hlower hsplit93 ⊢
          exact ⟨hlower, hsplit93⟩
        exact
          MiddleFaceCell92.candidate_not_isWeightedPerimeterMinimizer
            hcell candidate hcandidate
      · have hlower93 : (102931 / 100000 : ℝ) ≤ lam :=
          (not_le.mp hsplit93).le
        by_cases hsplit94 : lam ≤ (102941 / 100000 : ℝ)
        · have hcell : MiddleFaceCell93.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell93.lamInterval, MiddleFaceCell93.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower93 hsplit94 ⊢
            exact ⟨hlower93, hsplit94⟩
          exact
            MiddleFaceCell93.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
        · have hlower94 : (102941 / 100000 : ℝ) ≤ lam :=
            (not_le.mp hsplit94).le
          have hcell : MiddleFaceCell94.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell94.lamInterval, MiddleFaceCell94.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower94 hsplit95 ⊢
            exact ⟨hlower94, hsplit95⟩
          exact
            MiddleFaceCell94.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
    · have hlower95 : (102951 / 100000 : ℝ) ≤ lam :=
        (not_le.mp hsplit95).le
      by_cases hsplit96 : lam ≤ (102961 / 100000 : ℝ)
      · have hcell : MiddleFaceCell95.lamInterval.RealContains lam := by
          norm_num [MiddleFaceCell95.lamInterval, MiddleFaceCell95.brick,
            LeanSuffixReflective.QInterval.RealContains]
              at hlower95 hsplit96 ⊢
          exact ⟨hlower95, hsplit96⟩
        exact
          MiddleFaceCell95.candidate_not_isWeightedPerimeterMinimizer
            hcell candidate hcandidate
      · have hlower96 : (102961 / 100000 : ℝ) ≤ lam :=
          (not_le.mp hsplit96).le
        by_cases hsplit97 : lam ≤ (102971 / 100000 : ℝ)
        · have hcell : MiddleFaceCell96.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell96.lamInterval, MiddleFaceCell96.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower96 hsplit97 ⊢
            exact ⟨hlower96, hsplit97⟩
          exact
            MiddleFaceCell96.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
        · have hlower97 : (102971 / 100000 : ℝ) ≤ lam :=
            (not_le.mp hsplit97).le
          have hcell : MiddleFaceCell97.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell97.lamInterval, MiddleFaceCell97.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower97 hsplit98 ⊢
            exact ⟨hlower97, hsplit98⟩
          exact
            MiddleFaceCell97.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
  · have hlower98 : (102981 / 100000 : ℝ) ≤ lam :=
      (not_le.mp hsplit98).le
    by_cases hsplit101 : lam ≤ (103011 / 100000 : ℝ)
    · by_cases hsplit99 : lam ≤ (102991 / 100000 : ℝ)
      · have hcell : MiddleFaceCell98.lamInterval.RealContains lam := by
          norm_num [MiddleFaceCell98.lamInterval, MiddleFaceCell98.brick,
            LeanSuffixReflective.QInterval.RealContains]
              at hlower98 hsplit99 ⊢
          exact ⟨hlower98, hsplit99⟩
        exact
          MiddleFaceCell98.candidate_not_isWeightedPerimeterMinimizer
            hcell candidate hcandidate
      · have hlower99 : (102991 / 100000 : ℝ) ≤ lam :=
          (not_le.mp hsplit99).le
        by_cases hsplit100 : lam ≤ (103001 / 100000 : ℝ)
        · have hcell : MiddleFaceCell99.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell99.lamInterval, MiddleFaceCell99.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower99 hsplit100 ⊢
            exact ⟨hlower99, hsplit100⟩
          exact
            MiddleFaceCell99.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
        · have hlower100 : (103001 / 100000 : ℝ) ≤ lam :=
            (not_le.mp hsplit100).le
          have hcell : MiddleFaceCell100.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell100.lamInterval, MiddleFaceCell100.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower100 hsplit101 ⊢
            exact ⟨hlower100, hsplit101⟩
          exact
            MiddleFaceCell100.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
    · have hlower101 : (103011 / 100000 : ℝ) ≤ lam :=
        (not_le.mp hsplit101).le
      by_cases hsplit102 : lam ≤ (103021 / 100000 : ℝ)
      · have hcell : MiddleFaceCell101.lamInterval.RealContains lam := by
          norm_num [MiddleFaceCell101.lamInterval, MiddleFaceCell101.brick,
            LeanSuffixReflective.QInterval.RealContains]
              at hlower101 hsplit102 ⊢
          exact ⟨hlower101, hsplit102⟩
        exact
          MiddleFaceCell101.candidate_not_isWeightedPerimeterMinimizer
            hcell candidate hcandidate
      · have hlower102 : (103021 / 100000 : ℝ) ≤ lam :=
          (not_le.mp hsplit102).le
        by_cases hsplit103 : lam ≤ (103031 / 100000 : ℝ)
        · have hcell : MiddleFaceCell102.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell102.lamInterval, MiddleFaceCell102.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower102 hsplit103 ⊢
            exact ⟨hlower102, hsplit103⟩
          exact
            MiddleFaceCell102.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
        · have hlower103 : (103031 / 100000 : ℝ) ≤ lam :=
            (not_le.mp hsplit103).le
          have hcell : MiddleFaceCell103.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell103.lamInterval, MiddleFaceCell103.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower103 hupper ⊢
            exact ⟨hlower103, hupper⟩
          exact
            MiddleFaceCell103.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate

end MiddleFaceCells92To103
