/-
Copyright (c) 2026. Released under Apache 2.0 license.
-/
import MiddleFaceCell104
import MiddleFaceCell105
import MiddleFaceCell106
import MiddleFaceCell107
import MiddleFaceCell108
import MiddleFaceCell109
import MiddleFaceCell110
import MiddleFaceCell111
import MiddleFaceCell112

/-!
# Middle-face cells B0104 through B0112

Balanced branch-complete candidate exclusion over the closed union of exact
inventory bricks `B0104` through `B0112`.  Generated by
`middle_face_tiling/generate_lean_batch.py` from manifest payload hash
`d20c02a381696b4b1f3ea0790fcc089f0f026c4b9a2a23a50110287176334b4e`.
-/

noncomputable section

namespace MiddleFaceCells104To112

/-- Every modeled type-(iv) candidate in this closed batch fails
weighted-perimeter minimality. -/
theorem candidate_not_isWeightedPerimeterMinimizer
    {lam : ℝ}
    (hlower : (103041 / 100000 : ℝ) ≤ lam)
    (hupper : lam ≤ (25781 / 25000 : ℝ))
    (candidate : _root_.FourArcCandidate lam)
    (hcandidate : candidate.SatisfiesCMVTypeIVHypotheses) :
    ¬ candidate.IsWeightedPerimeterMinimizer := by
  by_cases hsplit108 : lam ≤ (103081 / 100000 : ℝ)
  · by_cases hsplit106 : lam ≤ (103061 / 100000 : ℝ)
    · by_cases hsplit105 : lam ≤ (103051 / 100000 : ℝ)
      · have hcell : MiddleFaceCell104.lamInterval.RealContains lam := by
          norm_num [MiddleFaceCell104.lamInterval, MiddleFaceCell104.brick,
            LeanSuffixReflective.QInterval.RealContains]
              at hlower hsplit105 ⊢
          exact ⟨hlower, hsplit105⟩
        exact
          MiddleFaceCell104.candidate_not_isWeightedPerimeterMinimizer
            hcell candidate hcandidate
      · have hlower105 : (103051 / 100000 : ℝ) ≤ lam :=
          (not_le.mp hsplit105).le
        have hcell : MiddleFaceCell105.lamInterval.RealContains lam := by
          norm_num [MiddleFaceCell105.lamInterval, MiddleFaceCell105.brick,
            LeanSuffixReflective.QInterval.RealContains]
              at hlower105 hsplit106 ⊢
          exact ⟨hlower105, hsplit106⟩
        exact
          MiddleFaceCell105.candidate_not_isWeightedPerimeterMinimizer
            hcell candidate hcandidate
    · have hlower106 : (103061 / 100000 : ℝ) ≤ lam :=
        (not_le.mp hsplit106).le
      by_cases hsplit107 : lam ≤ (103071 / 100000 : ℝ)
      · have hcell : MiddleFaceCell106.lamInterval.RealContains lam := by
          norm_num [MiddleFaceCell106.lamInterval, MiddleFaceCell106.brick,
            LeanSuffixReflective.QInterval.RealContains]
              at hlower106 hsplit107 ⊢
          exact ⟨hlower106, hsplit107⟩
        exact
          MiddleFaceCell106.candidate_not_isWeightedPerimeterMinimizer
            hcell candidate hcandidate
      · have hlower107 : (103071 / 100000 : ℝ) ≤ lam :=
          (not_le.mp hsplit107).le
        have hcell : MiddleFaceCell107.lamInterval.RealContains lam := by
          norm_num [MiddleFaceCell107.lamInterval, MiddleFaceCell107.brick,
            LeanSuffixReflective.QInterval.RealContains]
              at hlower107 hsplit108 ⊢
          exact ⟨hlower107, hsplit108⟩
        exact
          MiddleFaceCell107.candidate_not_isWeightedPerimeterMinimizer
            hcell candidate hcandidate
  · have hlower108 : (103081 / 100000 : ℝ) ≤ lam :=
      (not_le.mp hsplit108).le
    by_cases hsplit110 : lam ≤ (103101 / 100000 : ℝ)
    · by_cases hsplit109 : lam ≤ (103091 / 100000 : ℝ)
      · have hcell : MiddleFaceCell108.lamInterval.RealContains lam := by
          norm_num [MiddleFaceCell108.lamInterval, MiddleFaceCell108.brick,
            LeanSuffixReflective.QInterval.RealContains]
              at hlower108 hsplit109 ⊢
          exact ⟨hlower108, hsplit109⟩
        exact
          MiddleFaceCell108.candidate_not_isWeightedPerimeterMinimizer
            hcell candidate hcandidate
      · have hlower109 : (103091 / 100000 : ℝ) ≤ lam :=
          (not_le.mp hsplit109).le
        have hcell : MiddleFaceCell109.lamInterval.RealContains lam := by
          norm_num [MiddleFaceCell109.lamInterval, MiddleFaceCell109.brick,
            LeanSuffixReflective.QInterval.RealContains]
              at hlower109 hsplit110 ⊢
          exact ⟨hlower109, hsplit110⟩
        exact
          MiddleFaceCell109.candidate_not_isWeightedPerimeterMinimizer
            hcell candidate hcandidate
    · have hlower110 : (103101 / 100000 : ℝ) ≤ lam :=
        (not_le.mp hsplit110).le
      by_cases hsplit111 : lam ≤ (103111 / 100000 : ℝ)
      · have hcell : MiddleFaceCell110.lamInterval.RealContains lam := by
          norm_num [MiddleFaceCell110.lamInterval, MiddleFaceCell110.brick,
            LeanSuffixReflective.QInterval.RealContains]
              at hlower110 hsplit111 ⊢
          exact ⟨hlower110, hsplit111⟩
        exact
          MiddleFaceCell110.candidate_not_isWeightedPerimeterMinimizer
            hcell candidate hcandidate
      · have hlower111 : (103111 / 100000 : ℝ) ≤ lam :=
          (not_le.mp hsplit111).le
        by_cases hsplit112 : lam ≤ (103121 / 100000 : ℝ)
        · have hcell : MiddleFaceCell111.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell111.lamInterval, MiddleFaceCell111.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower111 hsplit112 ⊢
            exact ⟨hlower111, hsplit112⟩
          exact
            MiddleFaceCell111.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate
        · have hlower112 : (103121 / 100000 : ℝ) ≤ lam :=
            (not_le.mp hsplit112).le
          have hcell : MiddleFaceCell112.lamInterval.RealContains lam := by
            norm_num [MiddleFaceCell112.lamInterval, MiddleFaceCell112.brick,
              LeanSuffixReflective.QInterval.RealContains]
                at hlower112 hupper ⊢
            exact ⟨hlower112, hupper⟩
          exact
            MiddleFaceCell112.candidate_not_isWeightedPerimeterMinimizer
              hcell candidate hcandidate

end MiddleFaceCells104To112
